#!/usr/bin/env python3
# Parsec Cloud (https://parsec.cloud) Copyright (c) BUSL-1.1 2016-present Scille SAS

"""
Keep the editics protocol definition is sync between:
- server/parsec/editics_protocol.py (source of truth)
- client/editics/collaborative_protocol.js (autogenerated by this script)
"""

from __future__ import annotations

import argparse
import difflib
import re
import sys
import types
import typing
from pathlib import Path
from typing import Any
from unittest.mock import MagicMock
from uuid import UUID

REPO_ROOT = Path(__file__).resolve().parent.parent
EDITICS_PROTOCOL_PY = REPO_ROOT / "server/parsec/editics_protocol.py"
EDITICS_PROTOCOL_JS = REPO_ROOT / "client/editics/collaborative_protocol.js"

OPENING_MARK = "Auto-generated code"
CLOSING_MARK = "End of auto-generated code"

# Mock the dependencies needed by `editics_protocol.py` (i.e. `parsec._parsec`  & `pydantic`)
# This way we can run this script within installing the Python project (useful in the CI).


class BaseModel:
    pass


Field = MagicMock()
TypeAdapter = MagicMock()
DeviceID = MagicMock()

mock_pydantic = types.ModuleType("pydantic")
mock_pydantic.BaseModel = BaseModel  # type: ignore
mock_pydantic.Field = Field  # type: ignore
mock_pydantic.TypeAdapter = TypeAdapter  # type: ignore
mock_parsec = types.ModuleType("parsec")
mock_parsec_parsec = types.ModuleType("parsec._parsec")
mock_parsec_parsec.DeviceID = DeviceID  # type: ignore

sys.modules.update(
    {"pydantic": mock_pydantic, "parsec": mock_parsec, "parsec._parsec": mock_parsec_parsec}
)


def load_editics_protocol() -> dict[str, Any]:
    src = EDITICS_PROTOCOL_PY.read_text()
    namespace: dict[str, Any] = {"__name__": "editics_protocol"}

    exec(compile(src, str(EDITICS_PROTOCOL_PY), "exec"), namespace)

    # Build the `model_fields` pydantic normally provides by evaluating the
    # annotations.
    for obj in namespace.values():
        if not (isinstance(obj, type) and issubclass(obj, BaseModel) and obj is not BaseModel):
            continue
        model_fields = {}
        for field_name, raw_annotation in obj.__annotations__.items():
            annotation = (
                eval(raw_annotation, namespace)
                if isinstance(raw_annotation, str)
                else raw_annotation
            )
            if annotation is None:
                # `x: None = ...` is normalized to `NoneType` by pydantic
                annotation = type(None)
            field_info = MagicMock(annotation=annotation)
            # The field is optional if it has a default value
            field_info.is_optional.return_value = field_name not in obj.__dict__
            model_fields[field_name] = field_info
        obj.model_fields = model_fields  # type: ignore

    return namespace


# --- JSDoc generation --------------------------------------------------------


def generate_jsdoc_defs() -> list[str]:
    protocol = load_editics_protocol()
    lines = [
        "/* eslint-disable max-len */",
        "",
        "/**",
    ]
    for name, obj in protocol.items():
        if not name.startswith("Editics"):
            continue
        if isinstance(obj, MagicMock):
            # Pydantic helper (e.g. `EditicsClientEventAdapter`), not a protocol type
            continue
        if lines[-1] != "/**":
            lines.append(" *")
        lines.extend(_typedef_lines(name, obj))
    lines.append(" */")
    lines.append("")
    lines.append("/* eslint-enable max-len */")
    return lines


def _typedef_lines(name: str, obj: Any) -> list[str]:
    # `type X = Y` (PEP 695) alias, e.g. `@typedef {number} EditicsIndexUser`
    if isinstance(obj, typing.TypeAliasType):
        return [f" * @typedef {{{_js_type(obj.__value__)}}} {name}"]

    # Pydantic model, e.g. `@typedef {Object} EditicsClientEventAuth` + `@property`s
    if isinstance(obj, type) and issubclass(obj, BaseModel):
        lines = [f" * @typedef {{Object}} {name}"]
        for field_name, field in obj.model_fields.items():  # type: ignore
            if field.is_optional() and typing.get_origin(field.annotation) is not typing.Literal:
                field_name = f"[{field_name}]"
            lines.append(f" * @property {{{_js_type(field.annotation)}}} {field_name}")
        return lines

    # Union of events, i.e. `X = Annotated[A | B | ..., Field(discriminator="type")]`
    if typing.get_origin(obj) is typing.Annotated:
        (union, _discriminator_field) = typing.get_args(obj)
        members = "|".join(member.__name__ for member in typing.get_args(union))
        return [f" * @typedef {{{members}}} {name}"]

    raise AssertionError(f"Unknown editics protocol type: {name} = {obj!r}")


def _js_type(annotation: Any) -> str:
    """
    Render a Python annotation as the equivalent JSDoc type string.
    """
    # `Editics*`-named aliases are referenced by name (and get their own `@typedef`)
    if isinstance(annotation, typing.TypeAliasType):
        if annotation.__name__.startswith("Editics"):
            return annotation.__name__
        return _js_type(annotation.__value__)

    origin = typing.get_origin(annotation)
    if origin is typing.Literal:
        (value,) = typing.get_args(annotation)
        return f"'{value}'"
    if annotation is int:
        return "number"
    if annotation is bool:
        return "boolean"
    if annotation is str:
        return "string"
    if annotation is bytes:
        return "Uint8Array"
    # `EditicsParticipantID` is an UUID, `DeviceID` is serialized as its hex form
    if annotation is UUID or annotation is DeviceID:
        return "string"
    if annotation is typing.Any:
        return "*"
    if annotation is type(None):
        return "null"

    if origin in (typing.Union, types.UnionType):
        return "|".join(_js_type(member) for member in typing.get_args(annotation))
    if origin is list:
        (item_annotation,) = typing.get_args(annotation)
        item_type = _js_type(item_annotation)
        # Single-word types use the `T[]` syntax, the others `Array<T>`
        if re.fullmatch(r"\w+", item_type):
            return f"{item_type}[]"
        return f"Array<{item_type}>"
    if origin is dict:
        key_annotation, value_annotation = typing.get_args(annotation)
        key_type, value_type = _js_type(key_annotation), _js_type(value_annotation)
        # `Object<K,V>` is the idiom for a JSON object of arbitrary values
        if value_type == "*":
            return f"Object<{key_type},*>"
        return f"Record<{key_type}, {value_type}>"
    if origin is tuple:
        return "[" + ", ".join(_js_type(member) for member in typing.get_args(annotation)) + "]"
    if isinstance(annotation, type) and issubclass(annotation, BaseModel):
        if annotation.__name__.startswith("Editics"):
            # `Editics*`-named models are referenced by name (own `@typedef`)
            return annotation.__name__
        # Nested record model (e.g. `MessageRecord`), inlined
        return (
            "{"
            + ", ".join(
                f"{field_name}:{_js_type(field.annotation)}"
                for field_name, field in annotation.model_fields.items()  # type: ignore
            )
            + "}"
        )

    raise AssertionError(f"Unsupported editics protocol annotation: {annotation!r}")


# --- Check / fix --------------------------------------------------------------


def extract_generated_region(js_lines: list[str]) -> tuple[int, int, list[str]]:
    """
    Returns `(opening marker index, closing marker index, region lines)`
    """
    opening = [i for i, line in enumerate(js_lines) if OPENING_MARK in line]
    closing = [i for i, line in enumerate(js_lines) if CLOSING_MARK in line]
    assert len(opening) == 1 and len(closing) == 1 and opening[0] < closing[0], (
        f"Missing auto-generated code markers in {EDITICS_PROTOCOL_JS}"
    )
    start, end = opening[0], closing[0]
    return start, end, js_lines[start + 1 : end]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--fix", action="store_true", help="Regenerate the JSDoc instead of only checking it"
    )
    args = parser.parse_args()

    js_path = EDITICS_PROTOCOL_JS.relative_to(REPO_ROOT)
    js_lines = EDITICS_PROTOCOL_JS.read_text().splitlines()
    start, end, current = extract_generated_region(js_lines)
    expected = generate_jsdoc_defs()

    if current == expected:
        print(f"{js_path}: editics protocol JSDoc is up to date")
        return 0

    if not args.fix:
        sys.stdout.writelines(
            difflib.unified_diff(
                current,
                expected,
                fromfile=f"{js_path} (current)",
                tofile="server/parsec/editics_protocol.py (expected)",
            )
        )
        print(
            f"\n{js_path}: editics protocol JSDoc is out of sync, run with `--fix` to regenerate it"
        )
        return 1

    js_lines[start + 1 : end] = expected
    EDITICS_PROTOCOL_JS.write_text("\n".join(js_lines) + "\n")
    print(f"{js_path}: editics protocol JSDoc regenerated")
    return 0


if __name__ == "__main__":
    sys.exit(main())
