# Parsec Cloud (https://parsec.cloud) Copyright (c) AGPL-3.0 2016-present Scille SAS

from __future__ import annotations

class ProtocolErrorFields:
    @classmethod
    def NotHandled(cls) -> ProtocolErrorFields: ...
    @classmethod
    def BadRequest(cls, exc: str) -> ProtocolErrorFields: ...
    @property
    def exc(self) -> ProtocolErrorFields: ...

class ProtocolError(BaseException, ProtocolErrorFields): ...
