# Parsec Cloud (https://parsec.cloud) Copyright (c) BUSL-1.1 2016-present Scille SAS

# /!\ Autogenerated by misc/gen_protocol_typings.py, any modification will be lost !

from __future__ import annotations

from . import (
    account_delete_proceed,
    account_delete_send_validation_email,
    account_info,
    auth_method_create,
    auth_method_disable,
    auth_method_list,
    invite_self_list,
    organization_self_list,
    ping,
    vault_item_list,
    vault_item_recovery_list,
    vault_item_upload,
    vault_key_rotation,
)

class AnyCmdReq:
    @classmethod
    def load(
        cls, raw: bytes
    ) -> (
        account_delete_proceed.Req
        | account_delete_send_validation_email.Req
        | account_info.Req
        | auth_method_create.Req
        | auth_method_disable.Req
        | auth_method_list.Req
        | invite_self_list.Req
        | organization_self_list.Req
        | ping.Req
        | vault_item_list.Req
        | vault_item_recovery_list.Req
        | vault_item_upload.Req
        | vault_key_rotation.Req
    ): ...

__all__ = [
    "AnyCmdReq",
    "account_delete_proceed",
    "account_delete_send_validation_email",
    "account_info",
    "auth_method_create",
    "auth_method_disable",
    "auth_method_list",
    "invite_self_list",
    "organization_self_list",
    "ping",
    "vault_item_list",
    "vault_item_recovery_list",
    "vault_item_upload",
    "vault_key_rotation",
]
