# Parsec Cloud (https://parsec.cloud) Copyright (c) BUSL-1.1 2016-present Scille SAS

# /!\ Autogenerated by misc/gen_protocol_typings.py, any modification will be lost !

from __future__ import annotations

from . import (
    account_delete_send_validation_token,
    ping,
    vault_item_list,
    vault_item_recovery_list,
    vault_item_upload,
    vault_key_rotation,
)

class AnyCmdReq:
    @classmethod
    def load(
        cls, raw: bytes
    ) -> (
        account_delete_send_validation_token.Req
        | ping.Req
        | vault_item_list.Req
        | vault_item_recovery_list.Req
        | vault_item_upload.Req
        | vault_key_rotation.Req
    ): ...

__all__ = [
    "AnyCmdReq",
    "account_delete_send_validation_token",
    "ping",
    "vault_item_list",
    "vault_item_recovery_list",
    "vault_item_upload",
    "vault_key_rotation",
]
