# Parsec Cloud (https://parsec.cloud) Copyright (c) BUSL-1.1 2016-present Scille SAS

# /!\ Autogenerated by misc/gen_protocol_typings.py, any modification will be lost !

from __future__ import annotations

from parsec._parsec import AccountAuthMethodID

class Req:
    def __init__(self, auth_method_id: AccountAuthMethodID) -> None: ...
    def dump(self) -> bytes: ...
    @property
    def auth_method_id(self) -> AccountAuthMethodID: ...

class Rep:
    @staticmethod
    def load(raw: bytes) -> Rep: ...
    def dump(self) -> bytes: ...

class RepUnknownStatus(Rep):
    def __init__(self, status: str, reason: str | None) -> None: ...
    @property
    def status(self) -> str: ...
    @property
    def reason(self) -> str | None: ...

class RepOk(Rep):
    def __init__(
        self,
    ) -> None: ...

class RepAuthMethodNotFound(Rep):
    def __init__(
        self,
    ) -> None: ...

class RepAuthMethodAlreadyDisabled(Rep):
    def __init__(
        self,
    ) -> None: ...

class RepSelfDisableNotAllowed(Rep):
    def __init__(
        self,
    ) -> None: ...
