# Parsec Cloud (https://parsec.cloud) Copyright (c) BUSL-1.1 2016-present Scille SAS

# /!\ Autogenerated by misc/gen_protocol_typings.py, any modification will be lost !

from __future__ import annotations

from parsec._parsec import AccountAuthMethodID, SecretKey, UntrustedPasswordAlgorithm

class Req:
    def __init__(
        self,
        auth_method_password_algorithm: UntrustedPasswordAlgorithm | None,
        auth_method_mac_key: SecretKey,
        auth_method_id: AccountAuthMethodID,
        vault_key_access: bytes,
    ) -> None: ...
    def dump(self) -> bytes: ...
    @property
    def auth_method_id(self) -> AccountAuthMethodID: ...
    @property
    def auth_method_mac_key(self) -> SecretKey: ...
    @property
    def auth_method_password_algorithm(self) -> UntrustedPasswordAlgorithm | None: ...
    @property
    def vault_key_access(self) -> bytes: ...

class Rep:
    @staticmethod
    def load(raw: bytes) -> Rep: ...
    def dump(self) -> bytes: ...

class RepUnknownStatus(Rep):
    def __init__(self, status: str, reason: str | None) -> None: ...
    @property
    def status(self) -> str: ...
    @property
    def reason(self) -> str | None: ...

class RepOk(Rep):
    def __init__(
        self,
    ) -> None: ...

class RepAuthMethodIdAlreadyExists(Rep):
    def __init__(
        self,
    ) -> None: ...
