# Parsec Cloud (https://parsec.cloud) Copyright (c) BUSL-1.1 2016-present Scille SAS

# /!\ Autogenerated by misc/gen_protocol_typings.py, any modification will be lost !

from __future__ import annotations

from parsec._parsec import ActiveUsersLimit, DateTime, OrganizationID, UserID, UserProfile

class AllowedClientAgent:
    VALUES: tuple[AllowedClientAgent]
    NATIVE_ONLY: AllowedClientAgent
    NATIVE_OR_WEB: AllowedClientAgent

    @classmethod
    def from_str(cls, value: str) -> AllowedClientAgent: ...
    @property
    def str(self) -> str: ...

class AccountVaultStrategy:
    VALUES: tuple[AccountVaultStrategy]
    ALLOWED: AccountVaultStrategy
    FORBIDDEN: AccountVaultStrategy

    @classmethod
    def from_str(cls, value: str) -> AccountVaultStrategy: ...
    @property
    def str(self) -> str: ...

class OrganizationConfig:
    def __init__(
        self,
        is_expired: bool,
        user_profile_outsider_allowed: bool,
        active_users_limit: ActiveUsersLimit,
        allowed_client_agent: AllowedClientAgent,
        account_vault_strategy: AccountVaultStrategy,
    ) -> None: ...
    @property
    def account_vault_strategy(self) -> AccountVaultStrategy: ...
    @property
    def active_users_limit(self) -> ActiveUsersLimit: ...
    @property
    def allowed_client_agent(self) -> AllowedClientAgent: ...
    @property
    def is_expired(self) -> bool: ...
    @property
    def user_profile_outsider_allowed(self) -> bool: ...

class ActiveUser:
    def __init__(
        self,
        organization_id: OrganizationID,
        user_id: UserID,
        created_on: DateTime,
        is_frozen: bool,
        current_profile: UserProfile,
        organization_config: OrganizationConfig,
    ) -> None: ...
    @property
    def created_on(self) -> DateTime: ...
    @property
    def current_profile(self) -> UserProfile: ...
    @property
    def is_frozen(self) -> bool: ...
    @property
    def organization_config(self) -> OrganizationConfig: ...
    @property
    def organization_id(self) -> OrganizationID: ...
    @property
    def user_id(self) -> UserID: ...

class RevokedUser:
    def __init__(
        self,
        organization_id: OrganizationID,
        user_id: UserID,
        created_on: DateTime,
        revoked_on: DateTime,
        current_profile: UserProfile,
    ) -> None: ...
    @property
    def created_on(self) -> DateTime: ...
    @property
    def current_profile(self) -> UserProfile: ...
    @property
    def organization_id(self) -> OrganizationID: ...
    @property
    def revoked_on(self) -> DateTime: ...
    @property
    def user_id(self) -> UserID: ...

class Req:
    def __init__(
        self,
    ) -> None: ...
    def dump(self) -> bytes: ...

class Rep:
    @staticmethod
    def load(raw: bytes) -> Rep: ...
    def dump(self) -> bytes: ...

class RepUnknownStatus(Rep):
    def __init__(self, status: str, reason: str | None) -> None: ...
    @property
    def status(self) -> str: ...
    @property
    def reason(self) -> str | None: ...

class RepOk(Rep):
    def __init__(self, active: list[ActiveUser], revoked: list[RevokedUser]) -> None: ...
    @property
    def active(self) -> list[ActiveUser]: ...
    @property
    def revoked(self) -> list[RevokedUser]: ...
