# Parsec Cloud (https://parsec.cloud) Copyright (c) BUSL-1.1 2016-present Scille SAS

# /!\ Autogenerated by misc/gen_protocol_typings.py, any modification will be lost !

from __future__ import annotations

from parsec._parsec import DateTime, HashDigest

class VaultItemRecoveryVault:
    def __init__(
        self, auth_methods: list[VaultItemRecoveryAuthMethod], vault_items: dict[HashDigest, bytes]
    ) -> None: ...
    @property
    def auth_methods(self) -> list[VaultItemRecoveryAuthMethod]: ...
    @property
    def vault_items(self) -> dict[HashDigest, bytes]: ...

class VaultItemRecoveryAuthMethod:
    pass

class VaultItemRecoveryAuthMethodPassword(VaultItemRecoveryAuthMethod):
    def __init__(
        self,
        created_on: DateTime,
        created_by_ip: str,
        created_by_user_agent: str,
        vault_key_access: bytes,
        algorithm: PasswordAlgorithm,
    ) -> None: ...
    @property
    def algorithm(self) -> PasswordAlgorithm: ...
    @property
    def created_by_ip(self) -> str: ...
    @property
    def created_by_user_agent(self) -> str: ...
    @property
    def created_on(self) -> DateTime: ...
    @property
    def vault_key_access(self) -> bytes: ...

class PasswordAlgorithm:
    pass

class PasswordAlgorithmArgon2id(PasswordAlgorithm):
    def __init__(self, salt: bytes, opslimit: int, memlimit_kb: int, parallelism: int) -> None: ...
    @property
    def memlimit_kb(self) -> int: ...
    @property
    def opslimit(self) -> int: ...
    @property
    def parallelism(self) -> int: ...
    @property
    def salt(self) -> bytes: ...

class Req:
    def __init__(
        self,
    ) -> None: ...
    def dump(self) -> bytes: ...

class Rep:
    @staticmethod
    def load(raw: bytes) -> Rep: ...
    def dump(self) -> bytes: ...

class RepUnknownStatus(Rep):
    def __init__(self, status: str, reason: str | None) -> None: ...
    @property
    def status(self) -> str: ...
    @property
    def reason(self) -> str | None: ...

class RepOk(Rep):
    def __init__(
        self, current_vault: VaultItemRecoveryVault, previous_vaults: list[VaultItemRecoveryVault]
    ) -> None: ...
    @property
    def current_vault(self) -> VaultItemRecoveryVault: ...
    @property
    def previous_vaults(self) -> list[VaultItemRecoveryVault]: ...
