# Parsec Cloud (https://parsec.cloud) Copyright (c) AGPL-3.0 2016-present Scille SAS

from __future__ import annotations

from parsec._parsec import HumanHandle, UserID

class HumanFindResultItem:
    def __init__(
        self, user_id: UserID, human_handle: HumanHandle | None, revoked: bool
    ) -> None: ...
    @property
    def user_id(self) -> UserID: ...
    @property
    def human_handle(self) -> HumanHandle | None: ...
    @property
    def revoked(self) -> bool: ...

class Req:
    def __init__(
        self, query: str | None, omit_revoked: bool, omit_non_human: bool, page: int, per_page: int
    ) -> None: ...
    def dump(self) -> bytes: ...
    @property
    def query(self) -> str | None: ...
    @property
    def omit_revoked(self) -> bool: ...
    @property
    def omit_non_human(self) -> bool: ...
    @property
    def page(self) -> int: ...
    @property
    def per_page(self) -> int: ...

class Rep:
    @staticmethod
    def load(raw: bytes) -> Rep: ...
    def dump(self) -> bytes: ...

class RepUnknownStatus(Rep):
    def __init__(self, status: str, reason: str | None) -> None: ...
    @property
    def status(self) -> str: ...
    @property
    def reason(self) -> str | None: ...

class RepOk(Rep):
    def __init__(
        self, results: list[HumanFindResultItem], page: int, per_page: int, total: int
    ) -> None: ...
    @property
    def results(self) -> list[HumanFindResultItem]: ...
    @property
    def page(self) -> int: ...
    @property
    def per_page(self) -> int: ...
    @property
    def total(self) -> int: ...

class RepNotAllowed(Rep):
    def __init__(self, reason: str | None) -> None: ...
    @property
    def reason(self) -> str | None: ...
