# Parsec Cloud (https://parsec.cloud) Copyright (c) AGPL-3.0 2016-present Scille SAS

from __future__ import annotations

from typing import Callable

from parsec._parsec_pyi.ids import BlockID, EntryID
from parsec._parsec_pyi.manifest import BlockAccess

class FSBlockEventBus:
    def __init__(self) -> None: ...
    def connect_downloaded(
        self, workspace_id: EntryID, cb: Callable[[BlockAccess], None]
    ) -> None: ...
    def connect_purged(self, workspace_id: EntryID, cb: Callable[[set[BlockID]], None]) -> None: ...
    def disconnect_downloaded(self, workspace_id: EntryID) -> None: ...
    def disconnect_purged(self, workspace_id: EntryID) -> None: ...
    def send_downloaded(self, workspace_id: EntryID, block_access: BlockAccess) -> None: ...
    def send_purged(self, workspace_id: EntryID, block_ids: set[BlockID]) -> None: ...
