.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH parsec-cli-invite-claim 1  "claim " 
.SH NAME
parsec\-cli\-invite\-claim \- Claim an invitation
.SH SYNOPSIS
\fBparsec\-cli invite claim\fR [\fB\-\-password\-stdin\fR] [\fB\-d\fR|\fB\-\-data\-dir\fR] [\fB\-c\fR|\fB\-\-config\-dir\fR] [\fB\-\-use\-keyring\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIADDR\fR> 
.SH DESCRIPTION
Claim an invitation
.SH OPTIONS
.TP
\fB\-\-password\-stdin\fR
Read the password from stdin instead of TTY. This flag needs to be explicitly set (it does not have a env var)
.TP
\fB\-d\fR, \fB\-\-data\-dir\fR \fI<DATA_DIR>\fR [default: /home/redacted/.local/share/parsec3]
Parsec data directory
.RS
May also be specified with the \fBPARSEC_DATA_DIR\fR environment variable. 
.RE
.TP
\fB\-c\fR, \fB\-\-config\-dir\fR \fI<CONFIG_DIR>\fR [default: /home/redacted/.config/parsec3/libparsec]
Parsec config directory
.RS
May also be specified with the \fBPARSEC_CONFIG_DIR\fR environment variable. 
.RE
.TP
\fB\-\-use\-keyring\fR
Use keyring to store the password for the device
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIADDR\fR>
Server invitation address (e.g.: parsec3://127.0.0.1:41997/Org?no_ssl=true&a=claim_shamir_recovery&p=xBA2FaaizwKy4qG5cGDFlXaL` or http://127.0.0.1:41997/Org?no_ssl=true&a=claim_shamir_recovery&p=xBA2FaaizwKy4qG5cGDFlXaL`)
