.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH parsec-cli-organization-status 1  "status " 
.SH NAME
parsec\-cli\-organization\-status \- Get organization status
.SH SYNOPSIS
\fBparsec\-cli organization status\fR [\fB\-h\fR|\fB\-\-help\fR] <\fB\-o\fR|\fB\-\-organization\fR> <\fB\-t\fR|\fB\-\-token\fR> <\fB\-a\fR|\fB\-\-addr\fR> 
.SH DESCRIPTION
Get organization status
.SH OPTIONS
.TP
\fB\-o\fR, \fB\-\-organization\fR \fI<ORGANIZATION>\fR
Organization ID
.RS
May also be specified with the \fBPARSEC_ORGANIZATION_ID\fR environment variable. 
.RE
.TP
\fB\-t\fR, \fB\-\-token\fR \fI<TOKEN>\fR
Administration token
.RS
May also be specified with the \fBPARSEC_ADMINISTRATION_TOKEN\fR environment variable. 
.RE
.TP
\fB\-a\fR, \fB\-\-addr\fR \fI<ADDR>\fR
Server address (e.g: parsec3://127.0.0.1:6770?no_ssl=true)
.RS
May also be specified with the \fBPARSEC_SERVER_ADDR\fR environment variable. 
.RE
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
