.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH parsec-cli-organization-create 1  "create " 
.SH NAME
parsec\-cli\-organization\-create \- Create new organization
.SH SYNOPSIS
\fBparsec\-cli organization create\fR [\fB\-h\fR|\fB\-\-help\fR] <\fB\-t\fR|\fB\-\-token\fR> <\fB\-a\fR|\fB\-\-addr\fR> <\fIORGANIZATION\fR> 
.SH DESCRIPTION
Create new organization
.SH OPTIONS
.TP
\fB\-t\fR, \fB\-\-token\fR \fI<TOKEN>\fR
Administration token
.RS
May also be specified with the \fBPARSEC_ADMINISTRATION_TOKEN\fR environment variable. 
.RE
.TP
\fB\-a\fR, \fB\-\-addr\fR \fI<ADDR>\fR
Server address (e.g: parsec3://127.0.0.1:6770?no_ssl=true)
.RS
May also be specified with the \fBPARSEC_SERVER_ADDR\fR environment variable. 
.RE
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIORGANIZATION\fR>
The organization name that will be created
