.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH parsec-cli-organization-bootstrap 1  "bootstrap " 
.SH NAME
parsec\-cli\-organization\-bootstrap \- Configure new organization
.SH SYNOPSIS
\fBparsec\-cli organization bootstrap\fR [\fB\-\-auth\fR] [\fB\-\-password\-stdin\fR] [\fB\-\-sequester\-key\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fB\-\-addr\fR> <\fB\-d\fR|\fB\-\-device\-label\fR> <\fB\-l\fR|\fB\-\-label\fR> <\fB\-e\fR|\fB\-\-email\fR> 
.SH DESCRIPTION
Configure new organization
.SH OPTIONS
.TP
\fB\-\-auth\fR \fI<AUTH>\fR [default: password]
New authentication method for the new device
.br

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
keyring
.IP \(bu 2
password
.RE
.TP
\fB\-\-password\-stdin\fR
Read the password from stdin instead of TTY. This flag needs to be explicitly set (it does not have a env var)
.TP
\fB\-\-addr\fR \fI<ADDR>\fR
Bootstrap address (e.g: parsec3://127.0.0.1:6770/Org?no_ssl=true&action=bootstrap_organization&token=59961ba6dcc9b018d2fdc9da1c0c762b716a27cff30594562dc813e4b765871a or http://127.0.0.1:6770/Org?no_ssl=true&action=bootstrap_organization&token=59961ba6dcc9b018d2fdc9da1c0c762b716a27cff30594562dc813e4b765871a)
.TP
\fB\-d\fR, \fB\-\-device\-label\fR \fI<DEVICE_LABEL>\fR
Device label
.TP
\fB\-l\fR, \fB\-\-label\fR \fI<LABEL>\fR
User fullname
.TP
\fB\-e\fR, \fB\-\-email\fR \fI<EMAIL>\fR
User email
.TP
\fB\-\-sequester\-key\fR \fI<SEQUESTER_KEY>\fR
Sequester authority verify key path
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
