.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH parsec-cli-tos-accept 1  "accept " 
.SH NAME
parsec\-cli\-tos\-accept \- Accept Terms of Service of an organization
.SH SYNOPSIS
\fBparsec\-cli tos accept\fR [\fB\-\-password\-stdin\fR] [\fB\-c\fR|\fB\-\-config\-dir\fR] [\fB\-d\fR|\fB\-\-device\fR] [\fB\-\-yes\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Accept Terms of Service of an organization
.SH OPTIONS
.TP
\fB\-\-password\-stdin\fR
Read the password from stdin instead of TTY. This flag needs to be explicitly set (it does not have a env var)
.TP
\fB\-c\fR, \fB\-\-config\-dir\fR \fI<CONFIG_DIR>\fR [default: /home/redacted/.config/parsec3/libparsec]
Parsec config directory
.RS
May also be specified with the \fBPARSEC_CONFIG_DIR\fR environment variable. 
.RE
.TP
\fB\-d\fR, \fB\-\-device\fR \fI<DEVICE>\fR
Device ID
.RS
May also be specified with the \fBPARSEC_DEVICE_ID\fR environment variable. 
.RE
.TP
\fB\-\-yes\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
