.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH parsec-cli-device-overwrite-server-url 1  "overwrite-server-url " 
.SH NAME
parsec\-cli\-device\-overwrite\-server\-url \- Change the server URL for the device, this is normally not needed
.SH SYNOPSIS
\fBparsec\-cli device overwrite\-server\-url\fR [\fB\-\-password\-stdin\fR] [\fB\-d\fR|\fB\-\-device\fR] [\fB\-c\fR|\fB\-\-config\-dir\fR] <\fB\-s\fR|\fB\-\-server\-url\fR> [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Change the server URL for the device, this is normally not needed.
.PP
This is only useful if the organization gets migrated to a new server with a different domain name.
.SH OPTIONS
.TP
\fB\-\-password\-stdin\fR
Read the password from stdin instead of TTY. This flag needs to be explicitly set (it does not have a env var)
.TP
\fB\-d\fR, \fB\-\-device\fR \fI<DEVICE>\fR
Device ID
.RS
May also be specified with the \fBPARSEC_DEVICE_ID\fR environment variable. 
.RE
.TP
\fB\-c\fR, \fB\-\-config\-dir\fR \fI<CONFIG_DIR>\fR [default: /home/redacted/.config/parsec3/libparsec]
Parsec config directory
.RS
May also be specified with the \fBPARSEC_CONFIG_DIR\fR environment variable. 
.RE
.TP
\fB\-s\fR, \fB\-\-server\-url\fR \fI<SERVER_URL>\fR
The new server URL
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
