.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH parsec-cli-server 1  "server " 
.SH NAME
parsec\-cli\-server \- Contains subcommands related to server operations
.SH SYNOPSIS
\fBparsec\-cli server\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Contains subcommands related to server operations
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
parsec\-cli\-server\-stats(1)
Get a per\-organization report of server usage
.TP
parsec\-cli\-server\-help(1)
Print this message or the help of the given subcommand(s)
