.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH parsec-cli-invite 1  "invite " 
.SH NAME
parsec\-cli\-invite \- Contains subcommands related to invitation
.SH SYNOPSIS
\fBparsec\-cli invite\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Contains subcommands related to invitation
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
parsec\-cli\-invite\-cancel(1)
Cancel an invitation
.TP
parsec\-cli\-invite\-claim(1)
Claim an invitation
.TP
parsec\-cli\-invite\-greet(1)
Greet an invitation
.TP
parsec\-cli\-invite\-list(1)
List invitations
.TP
parsec\-cli\-invite\-user(1)
Create user invitation
.TP
parsec\-cli\-invite\-device(1)
Create device invitation
.TP
parsec\-cli\-invite\-shared\-recovery(1)
Create shared recovery invitation
.TP
parsec\-cli\-invite\-help(1)
Print this message or the help of the given subcommand(s)
