# Parsec Cloud (https://parsec.cloud) Copyright (c) BUSL-1.1 2016-present Scille SAS

# /!\ Autogenerated by misc/gen_protocol_typings.py, any modification will be lost !

from __future__ import annotations

from parsec._parsec import BlockID, DateTime, VlobID

class Req:
    def __init__(
        self, block_id: BlockID, realm_id: VlobID, key_index: int, block: bytes
    ) -> None: ...
    def dump(self) -> bytes: ...
    @property
    def block(self) -> bytes: ...
    @property
    def block_id(self) -> BlockID: ...
    @property
    def key_index(self) -> int: ...
    @property
    def realm_id(self) -> VlobID: ...

class Rep:
    @staticmethod
    def load(raw: bytes) -> Rep: ...
    def dump(self) -> bytes: ...

class RepUnknownStatus(Rep):
    def __init__(self, status: str, reason: str | None) -> None: ...
    @property
    def status(self) -> str: ...
    @property
    def reason(self) -> str | None: ...

class RepOk(Rep):
    def __init__(
        self,
    ) -> None: ...

class RepRealmNotFound(Rep):
    def __init__(
        self,
    ) -> None: ...

class RepBlockAlreadyExists(Rep):
    def __init__(
        self,
    ) -> None: ...

class RepAuthorNotAllowed(Rep):
    def __init__(
        self,
    ) -> None: ...

class RepBadKeyIndex(Rep):
    def __init__(self, last_realm_certificate_timestamp: DateTime) -> None: ...
    @property
    def last_realm_certificate_timestamp(self) -> DateTime: ...

class RepStoreUnavailable(Rep):
    def __init__(
        self,
    ) -> None: ...
