# Parsec Cloud (https://parsec.cloud) Copyright (c) BUSL-1.1 2016-present Scille SAS

# /!\ Autogenerated by misc/gen_protocol_typings.py, any modification will be lost !

from __future__ import annotations

from parsec._parsec import AttemptID, InvitationToken

class Req:
    def __init__(self, token: InvitationToken, attempt: AttemptID, reason: int) -> None: ...
    def dump(self) -> bytes: ...
    @property
    def attempt(self) -> AttemptID: ...
    @property
    def reason(self) -> int: ...
    @property
    def token(self) -> InvitationToken: ...

class Rep:
    @staticmethod
    def load(raw: bytes) -> Rep: ...
    def dump(self) -> bytes: ...

class RepUnknownStatus(Rep):
    def __init__(self, status: str, reason: str | None) -> None: ...
    @property
    def status(self) -> str: ...
    @property
    def reason(self) -> str | None: ...

class RepOk(Rep):
    def __init__(self, attempt: AttemptID) -> None: ...
    @property
    def attempt(self) -> AttemptID: ...

class RepInvitationNotFound(Rep):
    def __init__(
        self,
    ) -> None: ...

class RepInvitationCompleted(Rep):
    def __init__(
        self,
    ) -> None: ...

class RepInvitationCancelled(Rep):
    def __init__(
        self,
    ) -> None: ...

class RepAuthorNotAllowed(Rep):
    def __init__(
        self,
    ) -> None: ...

class RepAttemptNotFound(Rep):
    def __init__(
        self,
    ) -> None: ...

class RepAttemptNotJoined(Rep):
    def __init__(
        self,
    ) -> None: ...

class RepAttemptAlreadyCancelled(Rep):
    def __init__(
        self,
    ) -> None: ...
