# Parsec Cloud (https://parsec.cloud) Copyright (c) BUSL-1.1 2016-present Scille SAS

# /!\ Autogenerated by misc/gen_protocol_typings.py, any modification will be lost !

from __future__ import annotations

from parsec._parsec import InvitationToken

class InviteExchangeResetReason:
    VALUES: tuple[InviteExchangeResetReason]
    NORMAL: InviteExchangeResetReason
    BAD_SAS_CODE: InviteExchangeResetReason

    @classmethod
    def from_str(cls, value: str) -> InviteExchangeResetReason: ...
    @property
    def str(self) -> str: ...

class Req:
    def __init__(
        self,
        token: InvitationToken,
        step: int,
        greeter_payload: bytes,
        last: bool,
        reset_reason: InviteExchangeResetReason | None,
    ) -> None: ...
    def dump(self) -> bytes: ...
    @property
    def token(self) -> InvitationToken: ...
    @property
    def step(self) -> int: ...
    @property
    def greeter_payload(self) -> bytes: ...
    @property
    def last(self) -> bool: ...
    @property
    def reset_reason(self) -> InviteExchangeResetReason | None: ...

class Rep:
    @staticmethod
    def load(raw: bytes) -> Rep: ...
    def dump(self) -> bytes: ...

class RepUnknownStatus(Rep):
    def __init__(self, status: str, reason: str | None) -> None: ...
    @property
    def status(self) -> str: ...
    @property
    def reason(self) -> str | None: ...

class RepOk(Rep):
    def __init__(self, claimer_payload: bytes) -> None: ...
    @property
    def claimer_payload(self) -> bytes: ...

class RepStep0RequiresResetReason(Rep):
    def __init__(
        self,
    ) -> None: ...

class RepInvitationNotFound(Rep):
    def __init__(
        self,
    ) -> None: ...

class RepInvitationDeleted(Rep):
    def __init__(
        self,
    ) -> None: ...

class RepRetryNeeded(Rep):
    def __init__(
        self,
    ) -> None: ...

class RepEnrollmentWrongStep(Rep):
    def __init__(self, reason: InviteExchangeResetReason) -> None: ...
    @property
    def reason(self) -> InviteExchangeResetReason: ...
