# Parsec Cloud (https://parsec.cloud) Copyright (c) BUSL-1.1 2016-present Scille SAS

# /!\ Autogenerated by misc/gen_protocol_typings.py, any modification will be lost !

from __future__ import annotations

from parsec._parsec import AttemptID, HashDigest, InvitationToken, PublicKey

class GreeterStep:
    @classmethod
    def load(cls, raw: bytes) -> GreeterStep: ...

class GreeterStepWaitPeer(GreeterStep):
    def __init__(self, public_key: PublicKey) -> None: ...
    def dump(self) -> bytes: ...
    @property
    def public_key(self) -> PublicKey: ...

class GreeterStepGetHashedNonce(GreeterStep):
    def __init__(
        self,
    ) -> None: ...
    def dump(self) -> bytes: ...

class ClaimerStep:
    @classmethod
    def load(cls, raw: bytes) -> ClaimerStep: ...

class ClaimerStepWaitPeer(ClaimerStep):
    def __init__(self, public_key: PublicKey) -> None: ...
    def dump(self) -> bytes: ...
    @property
    def public_key(self) -> PublicKey: ...

class ClaimerStepSendHashedNonce(ClaimerStep):
    def __init__(self, hashed_nonce: HashDigest) -> None: ...
    def dump(self) -> bytes: ...
    @property
    def hashed_nonce(self) -> HashDigest: ...

class Req:
    def __init__(
        self, token: InvitationToken, attempt: AttemptID, greeter_step: GreeterStep
    ) -> None: ...
    def dump(self) -> bytes: ...
    @property
    def attempt(self) -> AttemptID: ...
    @property
    def greeter_step(self) -> GreeterStep: ...
    @property
    def token(self) -> InvitationToken: ...

class Rep:
    @staticmethod
    def load(raw: bytes) -> Rep: ...
    def dump(self) -> bytes: ...

class RepUnknownStatus(Rep):
    def __init__(self, status: str, reason: str | None) -> None: ...
    @property
    def status(self) -> str: ...
    @property
    def reason(self) -> str | None: ...

class RepOk(Rep):
    def __init__(self, claimer_step: ClaimerStep) -> None: ...
    @property
    def claimer_step(self) -> ClaimerStep: ...

class RepNotReady(Rep):
    def __init__(
        self,
    ) -> None: ...

class RepInvitationNotFound(Rep):
    def __init__(
        self,
    ) -> None: ...

class RepInvitationCompleted(Rep):
    def __init__(
        self,
    ) -> None: ...

class RepInvitationCancelled(Rep):
    def __init__(
        self,
    ) -> None: ...

class RepAuthorNotAllowed(Rep):
    def __init__(
        self,
    ) -> None: ...

class RepAttemptNotFound(Rep):
    def __init__(
        self,
    ) -> None: ...

class RepAttemptNotJoined(Rep):
    def __init__(
        self,
    ) -> None: ...

class RepAttemptCancelled(Rep):
    def __init__(
        self,
    ) -> None: ...

class RepStepTooAdvanced(Rep):
    def __init__(
        self,
    ) -> None: ...

class RepStepMismatch(Rep):
    def __init__(
        self,
    ) -> None: ...
