// Parsec Cloud (https://parsec.cloud) Copyright (c) BUSL-1.1 (eventually AGPL-3.0) 2016-present Scille SAS

//! Send Authenticated commands to the server.
//!
//! The HTTP-request will contain the following headers for authentication:
//!
//! ```text
//! Authorization: PARSEC-SIGN-ED25519
//! Author: [base64 string]
//! Timestamp: [DateTime UTC RFC3339 with millisecond]
//! Signature: [base64 ed25519 signature]
//! ```
//! The signature is generated by appending the following data:
//!
//! 1. `author` (in base64, contains in header `Author`)
//! 2. `timestamp` (date time UTC RFC3339 with millisecond, contains in header `Timestamp`)
//! 3. `body` (the http body in bytes)
//!
//! # Why using rfc 3339 instead of rfc 2822 ?
//!
//! > Because I can, that's why
//! > @me
//!
//! The reasons are listed [here](https://datatracker.ietf.org/doc/html/rfc3339#section-5)
//!
//! 1. Ordering
//! 2. Tradeoff between human readability and interoperability
//! 3. Redundant information (i.e.: we don't need the day of week)
//!
//! Beside the headers for authentication, we also add the header `API_VERSION` that contain the [parsec_api_protocol::ApiVersion]
//!

use base64::prelude::{Engine, BASE64_STANDARD};
use bytes::Bytes;
use reqwest::{
    header::{HeaderMap, HeaderValue, AUTHORIZATION, CONTENT_LENGTH, CONTENT_TYPE},
    Client, RequestBuilder, Url,
};
use std::fmt::Debug;
use std::{path::Path, sync::Arc};

use libparsec_platform_http_proxy::ProxyConfig;
use libparsec_types::prelude::*;

#[cfg(feature = "test-with-testbed")]
use crate::testbed::{get_send_hook, SendHookConfig};
use crate::{
    error::{CommandError, CommandResult},
    API_VERSION_HEADER_NAME, PARSEC_CONTENT_TYPE,
};

/// Method name that will be used for the header `Authorization` to indicate that will be using this method.
pub const PARSEC_AUTH_METHOD: &str = "PARSEC-SIGN-ED25519";

/// Factory that send commands in a authenticated context.
#[derive(Debug)]
pub struct AuthenticatedCmds {
    /// HTTP Client that contain the basic configuration to communicate with the server.
    client: Client,
    url: Url,
    device: Arc<LocalDevice>,
    author_header_value: HeaderValue,
    #[cfg(feature = "test-with-testbed")]
    send_hook: Arc<SendHookConfig>,
}

impl AuthenticatedCmds {
    pub fn new(
        config_dir: &Path,
        device: Arc<LocalDevice>,
        config: ProxyConfig,
    ) -> reqwest::Result<Self> {
        let client = {
            let builder = reqwest::ClientBuilder::default();
            let builder = config.configure_http_client(builder)?;
            builder.build()?
        };
        Ok(Self::from_client(client, config_dir, device))
    }

    pub fn from_client(client: Client, _config_dir: &Path, device: Arc<LocalDevice>) -> Self {
        let url = device.organization_addr.to_authenticated_http_url();

        #[cfg(feature = "test-with-testbed")]
        let send_hook = get_send_hook(_config_dir);

        let author_header_value =
            HeaderValue::from_str(&BASE64_STANDARD.encode(device.device_id.to_string().as_bytes()))
                .expect("base64 shouldn't contain invalid char");

        Self {
            client,
            url,
            device,
            author_header_value,
            #[cfg(feature = "test-with-testbed")]
            send_hook,
        }
    }

    pub fn addr(&self) -> &BackendOrganizationAddr {
        &self.device.organization_addr
    }

    pub async fn send<T>(&self, request: T) -> CommandResult<<T>::Response>
    where
        T: ProtocolRequest + Debug + 'static,
    {
        #[cfg(feature = "test-with-testbed")]
        let request = {
            match self.send_hook.high_level_send(request).await {
                crate::testbed::HighLevelSendResult::Resolved(rep) => return rep,
                crate::testbed::HighLevelSendResult::PassToLowLevel(req) => req,
            }
        };

        let request_body = request.dump()?;

        // Split non-generic code out of `send` to limit the amount of code generated
        // by monomorphization
        let response_body = self.internal_send(request_body).await?;

        Ok(T::load_response(&response_body)?)
    }

    async fn internal_send(&self, request_body: Vec<u8>) -> Result<Bytes, CommandError> {
        let request_builder = self.client.post(self.url.clone());

        let req = prepare_request(
            request_builder,
            &self.device.signing_key,
            self.author_header_value.clone(),
            request_body,
        );

        #[cfg(feature = "test-with-testbed")]
        let resp = self.send_hook.low_level_send(req).await?;
        #[cfg(not(feature = "test-with-testbed"))]
        let resp = req.send().await?;

        match resp.status().as_u16() {
            200 => {
                let response_body = resp.bytes().await?;
                Ok(response_body)
            }
            415 => Err(CommandError::BadContent),
            422 => Err(crate::error::unsupported_api_version_from_headers(
                resp.headers(),
            )),
            460 => Err(CommandError::ExpiredOrganization),
            461 => Err(CommandError::RevokedUser),
            // We typically use HTTP 503 in the tests to simulate server offline,
            // so it should behave just like if we were not able to connect
            503 => Err(CommandError::NoResponse(None)),
            _ => Err(CommandError::InvalidResponseStatus(resp.status())),
        }
    }
}

/// Prepare a new request, the body will be added to the Request using [RequestBuilder::body]
fn prepare_request(
    request_builder: RequestBuilder,
    signing_key: &SigningKey,
    author_header_value: HeaderValue,
    body: Vec<u8>,
) -> RequestBuilder {
    let request_builder = sign_request(request_builder, signing_key, author_header_value, &body);

    let mut content_headers = HeaderMap::with_capacity(3);
    content_headers.insert(
        API_VERSION_HEADER_NAME,
        HeaderValue::from_str(&libparsec_protocol::API_VERSION.to_string())
            .expect("api version must contains valid char"),
    );
    content_headers.insert(CONTENT_TYPE, HeaderValue::from_static(PARSEC_CONTENT_TYPE));
    content_headers.insert(
        CONTENT_LENGTH,
        HeaderValue::from_str(&body.len().to_string()).expect("numeric value are valid char"),
    );

    request_builder.headers(content_headers).body(body)
}

/// Sing a request by adding specific headers.
fn sign_request(
    request_builder: RequestBuilder,
    signing_key: &SigningKey,
    author_header_value: HeaderValue,
    body: &[u8],
) -> RequestBuilder {
    let timestamp = chrono::Utc::now().to_rfc3339_opts(chrono::SecondsFormat::Millis, true);
    let signature = signing_key.sign_only_signature(body);
    let signature = BASE64_STANDARD.encode(signature);

    let mut authorization_headers = HeaderMap::with_capacity(4);

    authorization_headers.insert(AUTHORIZATION, HeaderValue::from_static(PARSEC_AUTH_METHOD));
    authorization_headers.insert("Author", author_header_value);
    authorization_headers.insert(
        "Timestamp",
        HeaderValue::from_str(&timestamp)
            .expect("should contain only numeric char which are valid char"),
    );
    authorization_headers.insert(
        "Signature",
        HeaderValue::from_str(&signature).expect("base64 shouldn't contain invalid char"),
    );

    request_builder.headers(authorization_headers)
}
