# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: parsec2/vfs/vfs.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='parsec2/vfs/vfs.proto',
  package='vfs',
  syntax='proto3',
  serialized_pb=_b('\n\x15parsec2/vfs/vfs.proto\x12\x03vfs\"\xd7\x01\n\x07Request\x12&\n\x04type\x18\x01 \x01(\x0e\x32\x18.vfs.Request.RequestType\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\x0c\"\x84\x01\n\x0bRequestType\x12\x0f\n\x0b\x43REATE_FILE\x10\x00\x12\r\n\tREAD_FILE\x10\x01\x12\x0e\n\nWRITE_FILE\x10\x02\x12\x0f\n\x0b\x44\x45LETE_FILE\x10\x03\x12\x08\n\x04STAT\x10\x04\x12\x0c\n\x08LIST_DIR\x10\x05\x12\x0c\n\x08MAKE_DIR\x10\x06\x12\x0e\n\nREMOVE_DIR\x10\x07\"\x90\x01\n\x04Stat\x12\x0c\n\x04size\x18\x01 \x01(\x03\x12\r\n\x05\x63time\x18\x02 \x01(\x02\x12\r\n\x05mtime\x18\x03 \x01(\x02\x12\r\n\x05\x61time\x18\x04 \x01(\x02\x12$\n\x04type\x18\x05 \x01(\x0e\x32\x16.vfs.Stat.StatModeType\"\'\n\x0cStatModeType\x12\r\n\tDIRECTORY\x10\x00\x12\x08\n\x04\x46ILE\x10\x01\"\xd9\x01\n\x08Response\x12\x31\n\x0bstatus_code\x18\x01 \x01(\x0e\x32\x1c.vfs.Response.StatusCodeType\x12\x11\n\terror_msg\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\x0c\x12\x0c\n\x04size\x18\x04 \x01(\x03\x12\x10\n\x08list_dir\x18\x05 \x03(\t\x12\x17\n\x04stat\x18\x06 \x01(\x0b\x32\t.vfs.Stat\"=\n\x0eStatusCodeType\x12\x06\n\x02OK\x10\x00\x12\x0f\n\x0b\x42\x41\x44_REQUEST\x10\x02\x12\x12\n\x0e\x46ILE_NOT_FOUND\x10\x03\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_REQUEST_REQUESTTYPE = _descriptor.EnumDescriptor(
  name='RequestType',
  full_name='vfs.Request.RequestType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CREATE_FILE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='READ_FILE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WRITE_FILE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DELETE_FILE', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STAT', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LIST_DIR', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MAKE_DIR', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REMOVE_DIR', index=7, number=7,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=114,
  serialized_end=246,
)
_sym_db.RegisterEnumDescriptor(_REQUEST_REQUESTTYPE)

_STAT_STATMODETYPE = _descriptor.EnumDescriptor(
  name='StatModeType',
  full_name='vfs.Stat.StatModeType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DIRECTORY', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FILE', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=354,
  serialized_end=393,
)
_sym_db.RegisterEnumDescriptor(_STAT_STATMODETYPE)

_RESPONSE_STATUSCODETYPE = _descriptor.EnumDescriptor(
  name='StatusCodeType',
  full_name='vfs.Response.StatusCodeType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BAD_REQUEST', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FILE_NOT_FOUND', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=552,
  serialized_end=613,
)
_sym_db.RegisterEnumDescriptor(_RESPONSE_STATUSCODETYPE)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='vfs.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='vfs.Request.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='path', full_name='vfs.Request.path', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='content', full_name='vfs.Request.content', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REQUEST_REQUESTTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=246,
)


_STAT = _descriptor.Descriptor(
  name='Stat',
  full_name='vfs.Stat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='size', full_name='vfs.Stat.size', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ctime', full_name='vfs.Stat.ctime', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mtime', full_name='vfs.Stat.mtime', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='atime', full_name='vfs.Stat.atime', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='vfs.Stat.type', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _STAT_STATMODETYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=249,
  serialized_end=393,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='vfs.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status_code', full_name='vfs.Response.status_code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error_msg', full_name='vfs.Response.error_msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='content', full_name='vfs.Response.content', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='size', full_name='vfs.Response.size', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='list_dir', full_name='vfs.Response.list_dir', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stat', full_name='vfs.Response.stat', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RESPONSE_STATUSCODETYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=396,
  serialized_end=613,
)

_REQUEST.fields_by_name['type'].enum_type = _REQUEST_REQUESTTYPE
_REQUEST_REQUESTTYPE.containing_type = _REQUEST
_STAT.fields_by_name['type'].enum_type = _STAT_STATMODETYPE
_STAT_STATMODETYPE.containing_type = _STAT
_RESPONSE.fields_by_name['status_code'].enum_type = _RESPONSE_STATUSCODETYPE
_RESPONSE.fields_by_name['stat'].message_type = _STAT
_RESPONSE_STATUSCODETYPE.containing_type = _RESPONSE
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Stat'] = _STAT
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'parsec2.vfs.vfs_pb2'
  # @@protoc_insertion_point(class_scope:vfs.Request)
  ))
_sym_db.RegisterMessage(Request)

Stat = _reflection.GeneratedProtocolMessageType('Stat', (_message.Message,), dict(
  DESCRIPTOR = _STAT,
  __module__ = 'parsec2.vfs.vfs_pb2'
  # @@protoc_insertion_point(class_scope:vfs.Stat)
  ))
_sym_db.RegisterMessage(Stat)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'parsec2.vfs.vfs_pb2'
  # @@protoc_insertion_point(class_scope:vfs.Response)
  ))
_sym_db.RegisterMessage(Response)


# @@protoc_insertion_point(module_scope)
