# Parsec Cloud (https://parsec.cloud) Copyright (c) BUSL-1.1 2016-present Scille SAS
from __future__ import annotations

from datetime import datetime
from pathlib import Path

import click

from parsec._parsec import (
    OrganizationID,
    SequesterServiceID,
    VlobID,
)
from parsec.cli.options import blockstore_server_options, db_server_options, debug_config_options
from parsec.cli.utils import cli_exception_handler, operation
from parsec.components.blockstore import blockstore_factory
from parsec.components.postgresql.sequester_export import RealmExporter
from parsec.components.sequester import (
    SequesterServiceType,
)
from parsec.config import BaseBlockStoreConfig

SERVICE_TYPE_CHOICES: dict[str, SequesterServiceType] = {
    service.value: service for service in SequesterServiceType
}


@click.command(short_help="Generate a certificate for a new sequester service")
@click.option("--service-label", type=str, help="New service name", required=True)
@click.option(
    "--service-public-key",
    help="The service encryption public key used to encrypt data to the sequester service",
    type=click.Path(exists=True, file_okay=True, dir_okay=False, path_type=Path),
    required=True,
)
@click.option(
    "--authority-private-key",
    help="The private authority key use. Used to sign the encryption key.",
    type=click.Path(exists=True, file_okay=True, dir_okay=False, path_type=Path),
    required=True,
)
@click.option(
    "--output",
    "-o",
    help="File to write the sequester service certificate into.",
    type=click.File("w", encoding="utf8"),
    required=True,
    metavar="CERTIFICATE.pem",
)
# Add --debug & --version
@debug_config_options
def generate_service_certificate(
    service_label: str,
    service_public_key: Path,
    authority_private_key: Path,
    output: click.utils.LazyFile,
    debug: bool,
) -> None:
    with cli_exception_handler(debug):
        raise NotImplementedError


@click.command(short_help="Register a new sequester service from it existing certificate")
@click.option(
    "--service-certificate",
    help="File containing the sequester service certificate (previously generated by `generate_service_certificate` command).",
    type=click.File("r", encoding="utf8"),
    required=True,
    metavar="CERTIFICATE.pem",
)
@click.option(
    "--organization",
    type=OrganizationID,
    help="Organization ID where to register the service",
    required=True,
)
@click.option(
    "--service-type",
    type=click.Choice(list(SERVICE_TYPE_CHOICES.keys()), case_sensitive=False),
    default=SequesterServiceType.STORAGE.value,
    help="Service type",
)
@click.option(
    "--webhook-url",
    type=str,
    default=None,
    help="[Service Type webhook only] webhook url used to send encrypted service data",
)
@db_server_options
# Add --debug & --version
@debug_config_options
def import_service_certificate(
    service_certificate: click.utils.LazyFile,
    organization: OrganizationID,
    db: str,
    db_max_connections: int,
    db_min_connections: int,
    service_type: str,
    webhook_url: str | None,
    debug: bool,
) -> None:
    with cli_exception_handler(debug):
        raise NotImplementedError


@click.command(short_help="Register a new sequester service")
@click.option(
    "--service-public-key",
    help="The service encryption public key used to encrypt data to the sequester service",
    type=click.Path(exists=True, file_okay=True, dir_okay=False, path_type=Path),
    required=True,
)
@click.option(
    "--authority-private-key",
    help="The private authority key use. Used to sign the encryption key.",
    type=click.Path(exists=True, file_okay=True, dir_okay=False, path_type=Path),
    required=True,
)
@click.option("--service-label", type=str, help="New service name", required=True)
@click.option(
    "--organization",
    type=OrganizationID,
    help="Organization ID where to register the service",
    required=True,
)
@click.option(
    "--service-type",
    type=click.Choice(list(SERVICE_TYPE_CHOICES.keys()), case_sensitive=False),
    default=SequesterServiceType.STORAGE.value,
    help="Service type",
)
@click.option(
    "--webhook-url",
    type=str,
    default=None,
    help="[Service Type webhook only] webhook url used to send encrypted service data",
)
@db_server_options
# Add --debug & --version
@debug_config_options
def create_service(
    service_public_key: Path,
    authority_private_key: Path,
    service_label: str,
    organization: OrganizationID,
    db: str,
    db_max_connections: int,
    db_min_connections: int,
    service_type: str,
    webhook_url: str | None,
    debug: bool,
) -> None:
    with cli_exception_handler(debug):
        raise NotImplementedError


@click.command(short_help="List available sequester services")
@click.option("--organization", type=OrganizationID, help="Organization ID", required=True)
@db_server_options
# Add --debug & --version
@debug_config_options
def list_services(
    organization: OrganizationID,
    db: str,
    db_max_connections: int,
    db_min_connections: int,
    debug: bool,
) -> None:
    with cli_exception_handler(debug):
        raise NotImplementedError


@click.command(short_help="Disable/re-enable a sequester service")
@click.option("--organization", type=OrganizationID, help="Organization ID", required=True)
@click.option(
    "--service",
    type=SequesterServiceID.from_hex,
    help="ID of the sequester service to update",
    required=True,
)
@click.option("--enable", is_flag=True, help="Enable service")
@click.option("--disable", is_flag=True, help="Disable service")
@db_server_options
# Add --debug & --version
@debug_config_options
def update_service(
    organization: OrganizationID,
    service: SequesterServiceID,
    db: str,
    db_max_connections: int,
    db_min_connections: int,
    enable: bool,
    disable: bool,
    debug: bool,
) -> None:
    with cli_exception_handler(debug):
        raise NotImplementedError


@click.command(short_help="Get information about user&realm accesses")
@click.option("--organization", type=OrganizationID, required=True)
@click.option("--filter", type=str, default="")
@db_server_options
def human_accesses(
    filter: str,
    organization: OrganizationID,
    db: str,
    db_max_connections: int,
    db_min_connections: int,
) -> None:
    raise NotImplementedError


@click.command(short_help="Open a realm export using the sequester service key and dump it content")
@click.option(
    "--service-decryption-key",
    help="Decryption key of the sequester service that have been use to create the realm export archive",
    type=click.Path(exists=True, file_okay=True, dir_okay=False, path_type=Path),
    required=True,
)
@click.option("--input", type=Path, required=True, help="Realm export archive")
@click.option(
    "--output", type=Path, required=True, help="Directory where to dump the content of the realm"
)
@click.option(
    "--filter-date",
    type=click.DateTime(formats=["%Y-%m-%d"]),
    required=False,
    help="Extract at a specific date; format year-month-day",
)
# Add --debug & --version
@debug_config_options
def extract_realm_export(
    service_decryption_key: Path,
    input: Path,
    output: Path,
    filter_date: datetime | None,
    debug: bool,
) -> int:
    with cli_exception_handler(debug):
        raise NotImplementedError


async def _export_realm(
    db_config: BackendDbConfig,
    blockstore_config: BaseBlockStoreConfig,
    organization_id: OrganizationID,
    realm_id: VlobID,
    service_id: SequesterServiceID,
    output: Path,
) -> None:
    if output.is_dir():
        # Output is pointing to a directory, use a default name for the database extract
        output_db_path = output / f"parsec-sequester-export-realm-{realm_id.hex}.sqlite"
    else:
        output_db_path = output

    output_db_display = click.style(str(output_db_path), fg="green")
    if output.exists():
        click.echo(
            f"File {output_db_display} already exists, continue the extract from where it was left"
        )
    else:
        click.echo(f"Creating {output_db_display}")

    click.echo(
        f"Use { click.style('^C', fg='yellow') } to stop the export,"
        " progress won't be lost when restarting the command"
    )

    async with db_config.pool() as pool:
        blockstore_component = blockstore_factory(config=blockstore_config, postgresql_pool=pool)

        async with RealmExporter.run(
            organization_id=organization_id,
            realm_id=realm_id,
            service_id=service_id,
            output_db_path=output_db_path,
            input_pool=pool,
            input_blockstore=blockstore_component,
        ) as exporter:
            # 1) Export vlobs

            with operation("Computing vlobs (i.e. file/folder metadata) to export"):
                (
                    vlob_total_count,
                    vlob_batch_offset_marker,
                ) = await exporter.compute_vlobs_export_status()

            if not vlob_total_count:
                click.echo("No more vlobs to export !")
            else:
                vlob_total_count_display = click.style(str(vlob_total_count), fg="green")
                click.echo(f"About {vlob_total_count_display} vlobs need to be exported")
                with click.progressbar(length=vlob_total_count, label="Exporting vlobs") as bar:
                    vlobs_exported_count = 0
                    vlob_batch_size = 1000
                    while True:
                        new_vlob_batch_offset_marker = await exporter.export_vlobs(
                            batch_size=vlob_batch_size, batch_offset_marker=vlob_batch_offset_marker
                        )
                        if new_vlob_batch_offset_marker <= vlob_batch_offset_marker:
                            break
                        vlob_batch_offset_marker = new_vlob_batch_offset_marker
                        # Note we might end up with vlobs_exported_count > vlob_total_count
                        # in case additional vlobs are created during the export, this is no
                        # big deal though (progress bar will stay at 100%)
                        bar.update(vlobs_exported_count)

            # Export blocks

            with operation("Computing blocks (i.e. files data) to export"):
                (
                    block_total_count,
                    block_batch_offset_marker,
                ) = await exporter.compute_blocks_export_status()

            if not block_total_count:
                click.echo("No more blocks to export !")
            else:
                block_total_count_display = click.style(str(block_total_count), fg="green")

                click.echo(f"About {block_total_count_display} blocks need to be exported")
                with click.progressbar(length=block_total_count, label="Exporting blocks") as bar:
                    blocks_exported_count = 0
                    block_batch_size = 100
                    while True:
                        new_block_batch_offset_marker = await exporter.export_blocks(
                            batch_size=block_batch_size,
                            batch_offset_marker=block_batch_offset_marker,
                        )
                        if new_block_batch_offset_marker <= block_batch_offset_marker:
                            break
                        block_batch_offset_marker = new_block_batch_offset_marker
                        # Note we might end up with blocks_exported_count > block_total_count
                        # in case additional blocks are created during the export, this is no
                        # big deal though (progress bar will stay at 100%)
                        bar.update(blocks_exported_count)


@click.command(short_help="Export a realm to consult it with a sequester service key")
@click.option("--organization", type=OrganizationID, required=True)
@click.option("--realm", type=VlobID.from_hex, required=True)
@click.option("--output", type=Path, required=True)
@db_server_options
@blockstore_server_options
# Add --debug & --version
@debug_config_options
def export_realm(
    organization: OrganizationID,
    realm: VlobID,
    service: SequesterServiceID,
    output: Path,
    db: str,
    db_max_connections: int,
    db_min_connections: int,
    blockstore: BaseBlockStoreConfig,
    debug: bool,
) -> None:
    with cli_exception_handler(debug):
        raise NotImplementedError
