class UnpackException(Exception): ...

class ExtraData(ValueError):
    def __init__(self, unpacked: object, extra: object) -> None: ...
    def __str__(self) -> str: ...

class FormatError(ValueError, UnpackException):
    def __init__(self, *args: object, **kwargs: object) -> None: ...
    def __str__(self) -> str: ...

class StackError(ValueError, UnpackException):
    def __init__(self, *args: object, **kwargs: object) -> None: ...
