[package]
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "parsec-cli"
publish.workspace = true
repository.workspace = true
version.workspace = true
autotests = false

[[bench]]
name = "minimal_short_id"
harness = false

[[test]]
name = "integration"
path = "tests/integration/mod.rs"

[features]
default = ["manpage", "shell-completion"]
use-libsodium = ["libparsec_crypto/use-libsodium"]
vendored-openssl = ["libparsec_crypto/vendored-openssl"]
vendored-dbus = ["libparsec/vendored-dbus"]
testenv = []
manpage = ["dep:clap_mangen"]
shell-completion = ["dep:clap_complete"]

[dependencies]
libparsec_client.workspace = true
libparsec_client_connection.workspace = true
libparsec_crypto.workspace = true
libparsec_platform_ipc.workspace = true
libparsec_platform_mountpoint.workspace = true
libparsec_types.workspace = true
libparsec.workspace = true

anyhow = { workspace = true }
clap = { workspace = true, features = ["default", "derive", "env", "cargo"] }
# `termination` feature enable handling of SIGHUP/SIGTERM on top of SIGINT
ctrlc = { workspace = true, features = ["termination"] }
data-encoding.workspace = true
dialoguer = { workspace = true, features = ["fuzzy-select"] }
futures.workspace = true
env_logger = { workspace = true, features = ["auto-color", "humantime", "regex"] }
log = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
rpassword = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["std"] }
serde_with.workspace = true
spinners = { workspace = true }
textwrap.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "io-std"] }
url = { workspace = true, optional = true }
uuid = { workspace = true }
itertools = { workspace = true, features = ["use_std"] }
thiserror = { workspace = true }
shadow-rs.workspace = true
clap_mangen = { workspace = true, features = ["env"], optional = true }
clap_complete = { workspace = true, optional = true }

[dev-dependencies]
libparsec = { workspace = true, features = ["cli-tests"] }
libparsec_tests_fixtures = { workspace = true }
parsec-cli = { path = ".", features = ["testenv"] }

assert_cmd = { workspace = true }
predicates = { workspace = true, features = ["regex"] }
regex.workspace = true
rstest = { workspace = true }
uuid = { workspace = true, features = ["v6", "std", "rng"] }

criterion = { workspace = true }

[build-dependencies]
shadow-rs = { workspace = true, features = ["git2", "build"] }

[target.'cfg(target_family = "unix")'.dev-dependencies]
# rexpect doesn't support Windows (see https://github.com/rust-cli/rexpect/issues/11)
rexpect = { workspace = true }

[target.'cfg(target_os = "windows")'.build-dependencies]
winfsp_wrs_build = { workspace = true }
