# Parsec Cloud (https://parsec.cloud) Copyright (c) BUSL-1.1 2016-present Scille SAS

from __future__ import annotations

from parsec._parsec_pyi.crypto import PublicKey, VerifyKey
from parsec._parsec_pyi.enumerate import UserProfile
from parsec._parsec_pyi.ids import DeviceID, DeviceLabel, HumanHandle, UserID

class PkiEnrollmentAnswerPayload:
    def __init__(
        self,
        user_id: UserID,
        device_id: DeviceID,
        device_label: DeviceLabel,
        human_handle: HumanHandle,
        profile: UserProfile,
        root_verify_key: VerifyKey,
    ): ...
    @property
    def user_id(self) -> UserID: ...
    @property
    def device_id(self) -> DeviceID: ...
    @property
    def device_label(self) -> DeviceLabel: ...
    @property
    def human_handle(self) -> HumanHandle: ...
    @property
    def profile(self) -> UserProfile: ...
    @property
    def root_verify_key(self) -> VerifyKey: ...
    @classmethod
    def load(cls, raw: bytes) -> PkiEnrollmentAnswerPayload: ...
    def dump(self) -> bytes: ...

class PkiEnrollmentSubmitPayload:
    def __init__(
        self,
        verify_key: VerifyKey,
        public_key: PublicKey,
        device_label: DeviceLabel,
        human_handle: HumanHandle,
    ) -> None: ...
    @property
    def verify_key(self) -> VerifyKey: ...
    @property
    def public_key(self) -> PublicKey: ...
    @property
    def device_label(self) -> DeviceLabel: ...
    @property
    def human_handle(self) -> HumanHandle: ...
    @classmethod
    def load(cls, raw: bytes) -> PkiEnrollmentSubmitPayload: ...
    def dump(self) -> bytes: ...

class X509Certificate:
    def __init__(
        self,
        issuer: dict[str, str],
        subject: dict[str, str],
        der_x509_certificate: bytes,
        certificate_sha1: bytes,
        certificate_id: str | None,
    ) -> None: ...
    def is_available_locally(self) -> bool: ...
    @property
    def subject_common_name(self) -> str | None: ...
    @property
    def subject_email_address(self) -> str | None: ...
    @property
    def issuer_common_name(self) -> str | None: ...
    @property
    def issuer(self) -> dict[str, str]: ...
    @property
    def subject(self) -> dict[str, str]: ...
    @property
    def der_x509_certificate(self) -> bytes: ...
    @property
    def certificate_sha1(self) -> bytes: ...
    @property
    def certificate_id(self) -> str | None: ...
