# Parsec Cloud (https://parsec.cloud) Copyright (c) BUSL-1.1 2016-present Scille SAS

from __future__ import annotations

from parsec._parsec_pyi.crypto import PublicKey, VerifyKey
from parsec._parsec_pyi.enumerate import UserProfile
from parsec._parsec_pyi.ids import DeviceID, DeviceLabel, HumanHandle, UserID
from parsec._parsec_pyi.time import DateTime

class PkiInvalidSignature(Exception): ...
class PkiUntrusted(Exception): ...
class PkiInvalidCertificateDER(ValueError): ...

class PkiSignatureAlgorithm:
    RSASSA_PSS_SHA256: PkiSignatureAlgorithm

    @classmethod
    def from_str(cls, value: str) -> PkiSignatureAlgorithm: ...
    @property
    def str(self) -> str: ...

class PkiEnrollmentAnswerPayload:
    def __init__(
        self,
        user_id: UserID,
        device_id: DeviceID,
        device_label: DeviceLabel,
        profile: UserProfile,
        root_verify_key: VerifyKey,
    ): ...
    @property
    def user_id(self) -> UserID: ...
    @property
    def device_id(self) -> DeviceID: ...
    @property
    def device_label(self) -> DeviceLabel: ...
    @property
    def profile(self) -> UserProfile: ...
    @property
    def root_verify_key(self) -> VerifyKey: ...
    @classmethod
    def load(cls, raw: bytes) -> PkiEnrollmentAnswerPayload: ...
    def dump(self) -> bytes: ...

class PkiEnrollmentSubmitPayload:
    def __init__(
        self,
        verify_key: VerifyKey,
        public_key: PublicKey,
        device_label: DeviceLabel,
    ) -> None: ...
    @property
    def verify_key(self) -> VerifyKey: ...
    @property
    def public_key(self) -> PublicKey: ...
    @property
    def device_label(self) -> DeviceLabel: ...
    @classmethod
    def load(cls, raw: bytes) -> PkiEnrollmentSubmitPayload: ...
    def dump(self) -> bytes: ...

class X509Certificate:
    @classmethod
    def try_from_pem(cls, raw_pem: bytes) -> X509Certificate: ...
    @classmethod
    def from_der(cls, raw_der: bytes) -> X509Certificate: ...
    def issuer(self) -> bytes: ...
    def subject(self) -> bytes: ...
    @property
    def der(self) -> bytes: ...

class X509CertificateInformation:
    @classmethod
    def load_der(cls, raw_der: bytes) -> X509CertificateInformation: ...
    def common_name(self) -> str | None: ...
    def emails(self) -> list[str]: ...
    def email(self) -> str | None: ...
    def human_handle(self) -> HumanHandle: ...

class TrustAnchor:
    @classmethod
    def try_from_pem(cls, raw_pem: bytes) -> TrustAnchor: ...
    @classmethod
    def from_der(cls, raw_der: bytes) -> TrustAnchor: ...
    @property
    def subject(self) -> bytes: ...

class SignedMessage:
    def __init__(self, algo: PkiSignatureAlgorithm, signature: bytes, message: bytes) -> None: ...

def load_submit_payload(
    signed_message: SignedMessage,
    der_certificate: bytes,
    intermediate_certs: list[bytes],
    trusted_roots: list[TrustAnchor],
    now: DateTime,
) -> PkiEnrollmentSubmitPayload: ...
def load_accept_payload(
    signed_message: SignedMessage,
    der_certificate: bytes,
    intermediate_certs: list[bytes],
    trusted_roots: list[TrustAnchor],
    now: DateTime,
) -> PkiEnrollmentAnswerPayload: ...
