# Parsec Cloud (https://parsec.cloud) Copyright (c) AGPL-3.0 2016-present Scille SAS

from __future__ import annotations

# Command Error
class BackendConnectionError(Exception): ...
class BackendProtocolError(BackendConnectionError): ...
class BackendNotAvailable(BackendConnectionError): ...
class BackendConnectionRefused(BackendConnectionError): ...
class BackendInvitationAlreadyUsed(BackendConnectionRefused): ...
class BackendInvitationNotFound(BackendConnectionRefused): ...
class BackendNotFoundError(BackendConnectionError): ...
class BackendInvitationOnExistingMember(BackendConnectionError): ...
class BackendOutOfBallparkError(BackendConnectionError): ...

# Data Error
class DataError(Exception): ...
class EntryNameError(ValueError): ...
class PkiEnrollmentError(Exception): ...
class PkiEnrollmentLocalPendingError(PkiEnrollmentError): ...
class PkiEnrollmentLocalPendingCannotReadError(PkiEnrollmentLocalPendingError): ...
class PkiEnrollmentLocalPendingCannotRemoveError(PkiEnrollmentLocalPendingError): ...
class PkiEnrollmentLocalPendingCannotSaveError(PkiEnrollmentLocalPendingError): ...
class PkiEnrollmentLocalPendingValidationError(PkiEnrollmentLocalPendingError): ...

# Invite Error
class InviteError(Exception): ...
class InviteActiveUsersLimitReachedError(InviteError): ...
class InviteAlreadyUsedError(InviteError): ...
class InviteNotFoundError(InviteError): ...
class InvitePeerResetError(InviteError): ...
