# Parsec Cloud (https://parsec.cloud) Copyright (c) BUSL-1.1 2016-present Scille SAS

# /!\ Autogenerated by misc/gen_protocol_typings.py, any modification will be lost !

from __future__ import annotations

from . import (
    account_create_proceed,
    account_create_send_validation_email,
    account_recover_proceed,
    account_recover_send_validation_email,
    auth_method_password_get_algorithm,
    ping,
)

class AnyCmdReq:
    @classmethod
    def load(
        cls, raw: bytes
    ) -> (
        account_create_proceed.Req
        | account_create_send_validation_email.Req
        | account_recover_proceed.Req
        | account_recover_send_validation_email.Req
        | auth_method_password_get_algorithm.Req
        | ping.Req
    ): ...

__all__ = [
    "AnyCmdReq",
    "account_create_proceed",
    "account_create_send_validation_email",
    "account_recover_proceed",
    "account_recover_send_validation_email",
    "auth_method_password_get_algorithm",
    "ping",
]
