# Parsec Cloud (https://parsec.cloud) Copyright (c) BUSL-1.1 2016-present Scille SAS

# /!\ Autogenerated by misc/gen_protocol_typings.py, any modification will be lost !

from __future__ import annotations

from parsec._parsec import (
    AccountAuthMethodID,
    EmailAddress,
    HumanHandle,
    SecretKey,
    UntrustedPasswordAlgorithm,
    ValidationCode,
)

class AccountCreateStep:
    pass

class AccountCreateStepNumber0CheckCode(AccountCreateStep):
    def __init__(self, validation_code: ValidationCode, email: EmailAddress) -> None: ...
    @property
    def email(self) -> EmailAddress: ...
    @property
    def validation_code(self) -> ValidationCode: ...

class AccountCreateStepNumber1Create(AccountCreateStep):
    def __init__(
        self,
        validation_code: ValidationCode,
        human_handle: HumanHandle,
        auth_method_password_algorithm: UntrustedPasswordAlgorithm | None,
        auth_method_mac_key: SecretKey,
        auth_method_id: AccountAuthMethodID,
        vault_key_access: bytes,
    ) -> None: ...
    @property
    def auth_method_id(self) -> AccountAuthMethodID: ...
    @property
    def auth_method_mac_key(self) -> SecretKey: ...
    @property
    def auth_method_password_algorithm(self) -> UntrustedPasswordAlgorithm | None: ...
    @property
    def human_handle(self) -> HumanHandle: ...
    @property
    def validation_code(self) -> ValidationCode: ...
    @property
    def vault_key_access(self) -> bytes: ...

class Req:
    def __init__(self, account_create_step: AccountCreateStep) -> None: ...
    def dump(self) -> bytes: ...
    @property
    def account_create_step(self) -> AccountCreateStep: ...

class Rep:
    @staticmethod
    def load(raw: bytes) -> Rep: ...
    def dump(self) -> bytes: ...

class RepUnknownStatus(Rep):
    def __init__(self, status: str, reason: str | None) -> None: ...
    @property
    def status(self) -> str: ...
    @property
    def reason(self) -> str | None: ...

class RepOk(Rep):
    def __init__(
        self,
    ) -> None: ...

class RepInvalidValidationCode(Rep):
    def __init__(
        self,
    ) -> None: ...

class RepSendValidationEmailRequired(Rep):
    def __init__(
        self,
    ) -> None: ...

class RepAuthMethodIdAlreadyExists(Rep):
    def __init__(
        self,
    ) -> None: ...
