# Parsec Cloud (https://parsec.cloud) Copyright (c) BUSL-1.1 2016-present Scille SAS

# /!\ Autogenerated by misc/gen_protocol_typings.py, any modification will be lost !

from __future__ import annotations

class Req:
    def __init__(
        self,
        scws_service_challenge_payload: bytes,
        scws_service_challenge_signature: bytes,
        scws_service_challenge_key_id: int,
        web_application_challenge_payload: bytes,
    ) -> None: ...
    def dump(self) -> bytes: ...
    @property
    def scws_service_challenge_key_id(self) -> int: ...
    @property
    def scws_service_challenge_payload(self) -> bytes: ...
    @property
    def scws_service_challenge_signature(self) -> bytes: ...
    @property
    def web_application_challenge_payload(self) -> bytes: ...

class Rep:
    @staticmethod
    def load(raw: bytes) -> Rep: ...
    def dump(self) -> bytes: ...

class RepUnknownStatus(Rep):
    def __init__(self, status: str, reason: str | None) -> None: ...
    @property
    def status(self) -> str: ...
    @property
    def reason(self) -> str | None: ...

class RepOk(Rep):
    def __init__(self, web_application_challenge_signature: bytes) -> None: ...
    @property
    def web_application_challenge_signature(self) -> bytes: ...

class RepNotAvailable(Rep):
    def __init__(
        self,
    ) -> None: ...

class RepUnknownScwsServiceChallengeKeyId(Rep):
    def __init__(
        self,
    ) -> None: ...

class RepInvalidScwsServiceChallengeSignature(Rep):
    def __init__(
        self,
    ) -> None: ...

class RepInvalidWebApplicationChallengePayload(Rep):
    def __init__(
        self,
    ) -> None: ...
