# Parsec Cloud (https://parsec.cloud) Copyright (c) BUSL-1.1 2016-present Scille SAS

# /!\ Autogenerated by misc/gen_protocol_typings.py, any modification will be lost !

from __future__ import annotations

class Req:
    def __init__(
        self,
        middleware_challenge: bytes,
        middleware_signature: bytes,
        server_challenge: bytes,
        pubkey_id: int,
    ) -> None: ...
    def dump(self) -> bytes: ...
    @property
    def middleware_challenge(self) -> bytes: ...
    @property
    def middleware_signature(self) -> bytes: ...
    @property
    def pubkey_id(self) -> int: ...
    @property
    def server_challenge(self) -> bytes: ...

class Rep:
    @staticmethod
    def load(raw: bytes) -> Rep: ...
    def dump(self) -> bytes: ...

class RepUnknownStatus(Rep):
    def __init__(self, status: str, reason: str | None) -> None: ...
    @property
    def status(self) -> str: ...
    @property
    def reason(self) -> str | None: ...

class RepOk(Rep):
    def __init__(self, server_signature: bytes) -> None: ...
    @property
    def server_signature(self) -> bytes: ...

class RepNotAvailable(Rep):
    def __init__(
        self,
    ) -> None: ...

class RepUnknownServicePublicKey(Rep):
    def __init__(
        self,
    ) -> None: ...

class RepInvalidServiceSignature(Rep):
    def __init__(
        self,
    ) -> None: ...
