# Parsec Cloud (https://parsec.cloud) Copyright (c) BUSL-1.1 2016-present Scille SAS

# /!\ Autogenerated by misc/gen_protocol_typings.py, any modification will be lost !

from __future__ import annotations

class AccountConfig:
    VALUES: tuple[AccountConfig]
    DISABLED: AccountConfig
    ENABLED_WITH_VAULT: AccountConfig
    ENABLED_WITHOUT_VAULT: AccountConfig

    @classmethod
    def from_str(cls, value: str) -> AccountConfig: ...
    @property
    def str(self) -> str: ...

class OrganizationBootstrapConfig:
    VALUES: tuple[OrganizationBootstrapConfig]
    WITH_BOOTSTRAP_TOKEN: OrganizationBootstrapConfig
    SPONTANEOUS: OrganizationBootstrapConfig

    @classmethod
    def from_str(cls, value: str) -> OrganizationBootstrapConfig: ...
    @property
    def str(self) -> str: ...

class OpenBaoConfig:
    pass

class OpenBaoConfigDisabled(OpenBaoConfig):
    def __init__(
        self,
    ) -> None: ...

class OpenBaoConfigEnabled(OpenBaoConfig):
    def __init__(
        self,
        server_url: str,
        secret: OpenBaoSecretConfig,
        transit_mount_path: str | None,
        auths: list[OpenBaoAuthConfig],
    ) -> None: ...
    @property
    def auths(self) -> list[OpenBaoAuthConfig]: ...
    @property
    def secret(self) -> OpenBaoSecretConfig: ...
    @property
    def server_url(self) -> str: ...
    @property
    def transit_mount_path(self) -> str | None: ...

class OpenBaoSecretConfig:
    pass

class OpenBaoSecretConfigKV2(OpenBaoSecretConfig):
    def __init__(self, mount_path: str) -> None: ...
    @property
    def mount_path(self) -> str: ...

class OpenBaoAuthConfig:
    def __init__(self, id: str, mount_path: str) -> None: ...
    @property
    def id(self) -> str: ...
    @property
    def mount_path(self) -> str: ...

class Req:
    def __init__(
        self,
    ) -> None: ...
    def dump(self) -> bytes: ...

class Rep:
    @staticmethod
    def load(raw: bytes) -> Rep: ...
    def dump(self) -> bytes: ...

class RepUnknownStatus(Rep):
    def __init__(self, status: str, reason: str | None) -> None: ...
    @property
    def status(self) -> str: ...
    @property
    def reason(self) -> str | None: ...

class RepOk(Rep):
    def __init__(
        self,
        account: AccountConfig,
        organization_bootstrap: OrganizationBootstrapConfig,
        openbao: OpenBaoConfig,
    ) -> None: ...
    @property
    def account(self) -> AccountConfig: ...
    @property
    def openbao(self) -> OpenBaoConfig: ...
    @property
    def organization_bootstrap(self) -> OrganizationBootstrapConfig: ...
