# Parsec Cloud (https://parsec.cloud) Copyright (c) BUSL-1.1 2016-present Scille SAS

# /!\ Autogenerated by misc/gen_protocol_typings.py, any modification will be lost !

from __future__ import annotations

from . import (
    invite_claimer_cancel_greeting_attempt,
    invite_claimer_start_greeting_attempt,
    invite_claimer_step,
    invite_info,
    ping,
)

class AnyCmdReq:
    @classmethod
    def load(
        cls, raw: bytes
    ) -> (
        invite_claimer_cancel_greeting_attempt.Req
        | invite_claimer_start_greeting_attempt.Req
        | invite_claimer_step.Req
        | invite_info.Req
        | ping.Req
    ): ...

__all__ = [
    "AnyCmdReq",
    "invite_claimer_cancel_greeting_attempt",
    "invite_claimer_start_greeting_attempt",
    "invite_claimer_step",
    "invite_info",
    "ping",
]
