services:
  parsec-proxy:
    depends_on:
      - parsec-server
    image: nginx:1.27-alpine
    container_name: parsec-proxy
    ports:
      - 443:443
      - 80:80
    secrets:
      - proxy-pem-crt
      - proxy-pem-key
    volumes:
      - ./parsec-nginx.conf:/etc/nginx/nginx.conf:ro

  parsec-postgres:
    image: postgres:16.10-alpine
    container_name: parsec-postgres
    environment:
      POSTGRES_USER: DB_USER
      POSTGRES_PASSWORD: DB_PASS
      POSTGRES_DB: parsec
    ports:
      # Expose PostgreSQL to localhost
      - 127.0.0.1:5432:5432
    volumes:
      - parsec-db-data:/var/lib/postgresql/data

  parsec-s3:
    image: quay.io/minio/minio:RELEASE.2024-09-13T20-26-02Z
    container_name: parsec-s3
    command: server --console-address ":9090" --certs-dir /opts/certs /data
    environment:
      MINIO_ROOT_USER: S3_ROOT_USER
      MINIO_ROOT_PASSWORD: S3_ROOT_PASS
    ports:
      # Admin console exposed to https://127.0.0.1:9090
      - 127.0.0.1:9090:9090
      # Expose S3 API to localhost
      - 127.0.0.1:9000:9000
    secrets:
      - source: ca-crt
        target: /opts/certs/CAs/ca.test.crt
      - source: s3-pem-crt
        target: /opts/certs/public.crt
      - source: s3-pem-key
        target: /opts/certs/private.key
    volumes:
      - parsec-object-data:/data

  parsec-smtp:
    image: mailhog/mailhog:v1.0.1
    container_name: parsec-smtp
    ports:
      - 1025:1025
      # Web interface exposed to http://127.0.0.1:8025
      - 127.0.0.1:8025:8025

  parsec-server:
    depends_on:
      - parsec-smtp
      - parsec-s3
      - parsec-postgres
    image: ghcr.io/scille/parsec-cloud/parsec-server:3.9.3-a.0.dev.20657+a5aa7a6
    restart: on-failure
    container_name: parsec-server
    env_file:
      - parsec.env
      - parsec-s3.env
      - parsec-db.env
      - parsec-smtp.env
      - parsec-admin-token.env
    environment:
      AWS_CA_BUNDLE: /run/secrets/ca-crt
    user: "1000"
    secrets:
      - ca-crt
      - parsec-pem-crt
      - parsec-pem-key
    ports:
      - 127.0.0.1:6777:6777

volumes:
  parsec-db-data: {}
  parsec-object-data: {}

secrets:
  parsec-pem-crt:
    file: ./tls/parsec.pem
  parsec-pem-key:
    file: ./tls/parsec-key.pem
  ca-crt:
    file: ./tls/ca.pem
  s3-pem-crt:
    file: ./tls/s3.pem
  s3-pem-key:
    file: ./tls/s3-key.pem
  proxy-pem-crt:
    file: ./tls/proxy.pem
  proxy-pem-key:
    file: ./tls/proxy-key.pem
