# Parsec Cloud (https://parsec.cloud) Copyright (c) AGPLv3 2019 Scille SAS

"""
This package is autogenerated from PyQt forms during parsec package
installation or by running `python setup.py generate_pyqt_forms`.
"""