# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/login_widget.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LoginWidget(object):
    def setupUi(self, LoginWidget):
        LoginWidget.setObjectName("LoginWidget")
        LoginWidget.resize(613, 366)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LoginWidget.sizePolicy().hasHeightForWidth())
        LoginWidget.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(LoginWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(LoginWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.combo_devices = QtWidgets.QComboBox(LoginWidget)
        self.combo_devices.setObjectName("combo_devices")
        self.verticalLayout.addWidget(self.combo_devices)
        self.line_edit_password = QtWidgets.QLineEdit(LoginWidget)
        self.line_edit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_edit_password.setObjectName("line_edit_password")
        self.verticalLayout.addWidget(self.line_edit_password)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.button_login = QtWidgets.QPushButton(LoginWidget)
        self.button_login.setEnabled(False)
        self.button_login.setObjectName("button_login")
        self.horizontalLayout.addWidget(self.button_login)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_error = QtWidgets.QLabel(LoginWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_error.setFont(font)
        self.label_error.setText("")
        self.label_error.setAlignment(QtCore.Qt.AlignCenter)
        self.label_error.setObjectName("label_error")
        self.verticalLayout.addWidget(self.label_error)
        self.label_2 = QtWidgets.QLabel(LoginWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.line_edit_register_login = QtWidgets.QLineEdit(LoginWidget)
        self.line_edit_register_login.setText("")
        self.line_edit_register_login.setObjectName("line_edit_register_login")
        self.verticalLayout.addWidget(self.line_edit_register_login)
        self.line_edit_register_password = QtWidgets.QLineEdit(LoginWidget)
        self.line_edit_register_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_edit_register_password.setObjectName("line_edit_register_password")
        self.verticalLayout.addWidget(self.line_edit_register_password)
        self.line_edit_register_password_check = QtWidgets.QLineEdit(LoginWidget)
        self.line_edit_register_password_check.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_edit_register_password_check.setObjectName("line_edit_register_password_check")
        self.verticalLayout.addWidget(self.line_edit_register_password_check)
        self.line_edit_register_device = QtWidgets.QLineEdit(LoginWidget)
        self.line_edit_register_device.setObjectName("line_edit_register_device")
        self.verticalLayout.addWidget(self.line_edit_register_device)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.button_register = QtWidgets.QPushButton(LoginWidget)
        self.button_register.setEnabled(False)
        self.button_register.setObjectName("button_register")
        self.horizontalLayout_2.addWidget(self.button_register)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_register_error = QtWidgets.QLabel(LoginWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_register_error.setFont(font)
        self.label_register_error.setText("")
        self.label_register_error.setAlignment(QtCore.Qt.AlignCenter)
        self.label_register_error.setObjectName("label_register_error")
        self.verticalLayout.addWidget(self.label_register_error)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)

        self.retranslateUi(LoginWidget)
        QtCore.QMetaObject.connectSlotsByName(LoginWidget)

    def retranslateUi(self, LoginWidget):
        _translate = QtCore.QCoreApplication.translate
        LoginWidget.setWindowTitle(_translate("LoginWidget", "Form"))
        self.label.setText(_translate("LoginWidget", "Log in"))
        self.line_edit_password.setPlaceholderText(_translate("LoginWidget", "Password"))
        self.button_login.setText(_translate("LoginWidget", "Log In"))
        self.label_2.setText(_translate("LoginWidget", "Or register a new user"))
        self.line_edit_register_login.setPlaceholderText(_translate("LoginWidget", "Login"))
        self.line_edit_register_password.setPlaceholderText(_translate("LoginWidget", "Password"))
        self.line_edit_register_password_check.setPlaceholderText(_translate("LoginWidget", "Password check"))
        self.line_edit_register_device.setPlaceholderText(_translate("LoginWidget", "Device"))
        self.button_register.setText(_translate("LoginWidget", "Register"))

