# Parsec Cloud (https://parsec.cloud) Copyright (c) BUSL-1.1 2016-present Scille SAS

# /!\ Autogenerated by misc/gen_protocol_typings.py, any modification will be lost !

from __future__ import annotations

from parsec._parsec import AsyncEnrollmentID, DateTime, PkiSignatureAlgorithm

class AcceptPayloadSignature:
    pass

class AcceptPayloadSignaturePKI(AcceptPayloadSignature):
    def __init__(
        self,
        signature: bytes,
        algorithm: PkiSignatureAlgorithm,
        accepter_der_x509_certificate: bytes,
        intermediate_der_x509_certificates: list[bytes],
    ) -> None: ...
    @property
    def accepter_der_x509_certificate(self) -> bytes: ...
    @property
    def algorithm(self) -> PkiSignatureAlgorithm: ...
    @property
    def intermediate_der_x509_certificates(self) -> list[bytes]: ...
    @property
    def signature(self) -> bytes: ...

class AcceptPayloadSignatureOpenBao(AcceptPayloadSignature):
    def __init__(self, signature: str, accepter_openbao_entity_id: str) -> None: ...
    @property
    def accepter_openbao_entity_id(self) -> str: ...
    @property
    def signature(self) -> str: ...

class Req:
    def __init__(
        self,
        enrollment_id: AsyncEnrollmentID,
        submitter_user_certificate: bytes,
        submitter_device_certificate: bytes,
        submitter_redacted_user_certificate: bytes,
        submitter_redacted_device_certificate: bytes,
        accept_payload: bytes,
        accept_payload_signature: AcceptPayloadSignature,
    ) -> None: ...
    def dump(self) -> bytes: ...
    @property
    def accept_payload(self) -> bytes: ...
    @property
    def accept_payload_signature(self) -> AcceptPayloadSignature: ...
    @property
    def enrollment_id(self) -> AsyncEnrollmentID: ...
    @property
    def submitter_device_certificate(self) -> bytes: ...
    @property
    def submitter_redacted_device_certificate(self) -> bytes: ...
    @property
    def submitter_redacted_user_certificate(self) -> bytes: ...
    @property
    def submitter_user_certificate(self) -> bytes: ...

class Rep:
    @staticmethod
    def load(raw: bytes) -> Rep: ...
    def dump(self) -> bytes: ...

class RepUnknownStatus(Rep):
    def __init__(self, status: str, reason: str | None) -> None: ...
    @property
    def status(self) -> str: ...
    @property
    def reason(self) -> str | None: ...

class RepOk(Rep):
    def __init__(
        self,
    ) -> None: ...

class RepAuthorNotAllowed(Rep):
    def __init__(
        self,
    ) -> None: ...

class RepInvalidCertificate(Rep):
    def __init__(
        self,
    ) -> None: ...

class RepInvalidAcceptPayload(Rep):
    def __init__(
        self,
    ) -> None: ...

class RepInvalidAcceptPayloadSignature(Rep):
    def __init__(
        self,
    ) -> None: ...

class RepSubmitAndAcceptIdentitySystemsMismatch(Rep):
    def __init__(
        self,
    ) -> None: ...

class RepInvalidDerX509Certificate(Rep):
    def __init__(
        self,
    ) -> None: ...

class RepInvalidX509Trustchain(Rep):
    def __init__(
        self,
    ) -> None: ...

class RepEnrollmentNotFound(Rep):
    def __init__(
        self,
    ) -> None: ...

class RepEnrollmentNoLongerAvailable(Rep):
    def __init__(
        self,
    ) -> None: ...

class RepActiveUsersLimitReached(Rep):
    def __init__(
        self,
    ) -> None: ...

class RepUserAlreadyExists(Rep):
    def __init__(
        self,
    ) -> None: ...

class RepHumanHandleAlreadyTaken(Rep):
    def __init__(
        self,
    ) -> None: ...

class RepTimestampOutOfBallpark(Rep):
    def __init__(
        self,
        ballpark_client_early_offset: float,
        ballpark_client_late_offset: float,
        server_timestamp: DateTime,
        client_timestamp: DateTime,
    ) -> None: ...
    @property
    def ballpark_client_early_offset(self) -> float: ...
    @property
    def ballpark_client_late_offset(self) -> float: ...
    @property
    def client_timestamp(self) -> DateTime: ...
    @property
    def server_timestamp(self) -> DateTime: ...

class RepRequireGreaterTimestamp(Rep):
    def __init__(self, strictly_greater_than: DateTime) -> None: ...
    @property
    def strictly_greater_than(self) -> DateTime: ...
