# Parsec Cloud (https://parsec.cloud) Copyright (c) BUSL-1.1 2016-present Scille SAS

# /!\ Autogenerated by misc/gen_protocol_typings.py, any modification will be lost !

from __future__ import annotations

from parsec._parsec import DateTime, VlobID

class Req:
    def __init__(
        self,
        common_after: DateTime | None,
        sequester_after: DateTime | None,
        shamir_recovery_after: DateTime | None,
        realm_after: dict[VlobID, DateTime],
    ) -> None: ...
    def dump(self) -> bytes: ...
    @property
    def common_after(self) -> DateTime | None: ...
    @property
    def realm_after(self) -> dict[VlobID, DateTime]: ...
    @property
    def sequester_after(self) -> DateTime | None: ...
    @property
    def shamir_recovery_after(self) -> DateTime | None: ...

class Rep:
    @staticmethod
    def load(raw: bytes) -> Rep: ...
    def dump(self) -> bytes: ...

class RepUnknownStatus(Rep):
    def __init__(self, status: str, reason: str | None) -> None: ...
    @property
    def status(self) -> str: ...
    @property
    def reason(self) -> str | None: ...

class RepOk(Rep):
    def __init__(
        self,
        common_certificates: list[bytes],
        sequester_certificates: list[bytes],
        shamir_recovery_certificates: list[bytes],
        realm_certificates: dict[VlobID, list[bytes]],
    ) -> None: ...
    @property
    def common_certificates(self) -> list[bytes]: ...
    @property
    def realm_certificates(self) -> dict[VlobID, list[bytes]]: ...
    @property
    def sequester_certificates(self) -> list[bytes]: ...
    @property
    def shamir_recovery_certificates(self) -> list[bytes]: ...
