# Parsec Cloud (https://parsec.cloud) Copyright (c) BUSL-1.1 2016-present Scille SAS

# /!\ Autogenerated by misc/gen_protocol_typings.py, any modification will be lost !

from __future__ import annotations

from parsec._parsec import DateTime, DeviceID, VlobID

class Req:
    def __init__(
        self,
        realm_id: VlobID,
        document_id: VlobID,
        key_index: int,
        timestamp: DateTime,
        encrypted_candidate_view_key: bytes,
        encrypted_candidate_edit_key: bytes | None,
    ) -> None: ...
    def dump(self) -> bytes: ...
    @property
    def document_id(self) -> VlobID: ...
    @property
    def encrypted_candidate_edit_key(self) -> bytes | None: ...
    @property
    def encrypted_candidate_view_key(self) -> bytes: ...
    @property
    def key_index(self) -> int: ...
    @property
    def realm_id(self) -> VlobID: ...
    @property
    def timestamp(self) -> DateTime: ...

class Rep:
    @staticmethod
    def load(raw: bytes) -> Rep: ...
    def dump(self) -> bytes: ...

class RepUnknownStatus(Rep):
    def __init__(self, status: str, reason: str | None) -> None: ...
    @property
    def status(self) -> str: ...
    @property
    def reason(self) -> str | None: ...

class RepOk(Rep):
    def __init__(
        self,
        author: DeviceID,
        timestamp: DateTime,
        key_index: int,
        encrypted_view_key: bytes,
        encrypted_edit_key: bytes | None,
        needed_common_certificate_timestamp: DateTime,
        needed_realm_certificate_timestamp: DateTime,
    ) -> None: ...
    @property
    def author(self) -> DeviceID: ...
    @property
    def encrypted_edit_key(self) -> bytes | None: ...
    @property
    def encrypted_view_key(self) -> bytes: ...
    @property
    def key_index(self) -> int: ...
    @property
    def needed_common_certificate_timestamp(self) -> DateTime: ...
    @property
    def needed_realm_certificate_timestamp(self) -> DateTime: ...
    @property
    def timestamp(self) -> DateTime: ...

class RepCryptpadUnavailable(Rep):
    def __init__(
        self,
    ) -> None: ...

class RepRealmNotFound(Rep):
    def __init__(
        self,
    ) -> None: ...

class RepRealmDeleted(Rep):
    def __init__(
        self,
    ) -> None: ...

class RepAuthorNotAllowed(Rep):
    def __init__(
        self,
    ) -> None: ...

class RepBadKeyIndex(Rep):
    def __init__(self, last_realm_certificate_timestamp: DateTime) -> None: ...
    @property
    def last_realm_certificate_timestamp(self) -> DateTime: ...

class RepTimestampOutOfBallpark(Rep):
    def __init__(
        self,
        ballpark_client_early_offset: float,
        ballpark_client_late_offset: float,
        server_timestamp: DateTime,
        client_timestamp: DateTime,
    ) -> None: ...
    @property
    def ballpark_client_early_offset(self) -> float: ...
    @property
    def ballpark_client_late_offset(self) -> float: ...
    @property
    def client_timestamp(self) -> DateTime: ...
    @property
    def server_timestamp(self) -> DateTime: ...
