# Parsec Cloud (https://parsec.cloud) Copyright (c) BUSL-1.1 2016-present Scille SAS

# /!\ Autogenerated by misc/gen_protocol_typings.py, any modification will be lost !

from __future__ import annotations

from . import ping

class AnyCmdReq:
    @classmethod
    def load(cls, raw: bytes) -> ping.Req: ...

__all__ = ["AnyCmdReq", "ping"]
