# Parsec Cloud (https://parsec.cloud) Copyright (c) BUSL-1.1 2016-present Scille SAS

# /!\ Autogenerated by misc/gen_protocol_typings.py, any modification will be lost !

from __future__ import annotations

from . import account_send_email_validation_token, ping

class AnyCmdReq:
    @classmethod
    def load(cls, raw: bytes) -> account_send_email_validation_token.Req | ping.Req: ...

__all__ = ["AnyCmdReq", "account_send_email_validation_token", "ping"]
