<#
.SYNOPSIS
  Import a test PKI

.DESCRIPTION
  Import a test PKI generated by the script `./gen_test_pki.py`
.PARAMETER ImportPath
    Path where the test PKI was generated
.PARAMETER OnlyCleanup
    Remove previously imported PKI
.PARAMETER NoCleanup
        If set, do not wait for ENTER to automatically remove the imported PKI on exit
#>
[CmdletBinding()]
param(
    [switch] $OnlyCleanup,
    [switch] $NoCleanup,
    [string] $ImportPath = ".\test-pki"
)

# Store the thumbprints of the imported certificates here for later cleanup
$register_file = ".\.imported-test-pki.txt"

function Cleanup-Test-PKI {
    if (-not (Test-Path -Path $register_file -PathType Leaf)) {
        echo "$register_file does not exist, skipping cleanup"
        return
    }

    $thumbprints = Get-Content -Path $register_file

    Get-ChildItem -Recurse Cert:\CurrentUser `
        | Where-Object { $thumbprints -contains $_.Thumbprint } `
        | Remove-Item -Verbose
    Clear-Content -Path $register_file
}

# Perform cleanup
echo "Removing Previous Test PKI if any"
Cleanup-Test-PKI

if ($OnlyCleanup) {
    exit
}

function On-Exit {
    echo "Cleanup Test PKI before exit"
    Cleanup-Test-PKI
}

# Cleanup test pki on Ctrl+C, Stop Event or Shutdown
if (-not $NoCleanup) {
    $null = Register-EngineEvent -SourceIdentifier PowerShell.Exiting -SupportEvent -Action { On-Exit }
}

function Import-Certificates {
    param (
        [Parameter(mandatory=$true)]
        [string] $ImportPath,
        [Parameter(mandatory=$true)]
        [string] $Store,
        [bool] $UsePfx = $false
    )

    if ($UsePfx) {
        $import_cmd="Import-PfxCertificate"
        $filter_ext="*.pfx"
    } else {
        $import_cmd="Import-Certificate"
        $filter_ext="*.crt"
    }

    return Get-ChildItem -Path $ImportPath -Filter $filter_ext `
        | ForEach-Object { & $import_cmd -CertStoreLocation Cert:\CurrentUser\$Store -FilePath $_.FullName }
}

function ImportNRegister-Certificates {
    param (
        [Parameter(mandatory=$true)]
        [string] $ImportPath,
        [Parameter(mandatory=$true)]
        [string] $Store,
        [switch] $UsePfx
    )

    return Import-Certificates -ImportPath $ImportPath -Store $Store -UsePfx $UsePfx `
        | ForEach-Object { echo $_.Thumbprint } `
        | Add-Content -Path $register_file
}

ImportNRegister-Certificates -ImportPath $ImportPath\Root -Store Root
ImportNRegister-Certificates -ImportPath $ImportPath\Intermediate -Store CA
ImportNRegister-Certificates -ImportPath $ImportPath\Cert -Store MY -UsePfx

if ($NoCleanup) {
    Write-Output "Certificates are installed and ready to use."
    return
}

try {
    Write-Output "Certificates are installed and ready to use. Once you are done, press ENTER to uninstall them..."
    do {
        $key = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
    } while ($key.VirtualKeyCode -ne [ConsoleKey]::ENTER)
}
finally {
    On-Exit
}
