# Parsec Cloud (https://parsec.cloud) Copyright (c) AGPLv3 2019 Scille SAS

from parsec.api.protocol import (
    APIV1_ADMINISTRATION_CMDS,
    APIV1_ANONYMOUS_CMDS,
    APIV1_AUTHENTICATED_CMDS,
    AUTHENTICATED_CMDS,
    INVITED_CMDS,
)

ALL_CMDS = (
    AUTHENTICATED_CMDS
    | INVITED_CMDS
    | APIV1_ADMINISTRATION_CMDS
    | APIV1_AUTHENTICATED_CMDS
    | APIV1_ANONYMOUS_CMDS
)
