class Range:
    def __init__(self, min=None, max=None, error=None): ...
    def __call__(self, value): ...

class Length:
    def __init__(self, min=None, max=None, error=None, equal=None): ...
    def __call__(self, value): ...
