# Parsec Cloud (https://parsec.cloud) Copyright (c) BUSL-1.1 2016-present Scille SAS

# /!\ Autogenerated by misc/gen_protocol_typings.py, any modification will be lost !

from __future__ import annotations

from . import (
    async_enrollment_cancel,
    async_enrollment_info,
    async_enrollment_submit,
    organization_bootstrap,
    ping,
)

class AnyCmdReq:
    @classmethod
    def load(
        cls, raw: bytes
    ) -> (
        async_enrollment_cancel.Req
        | async_enrollment_info.Req
        | async_enrollment_submit.Req
        | organization_bootstrap.Req
        | ping.Req
    ): ...

__all__ = [
    "AnyCmdReq",
    "async_enrollment_cancel",
    "async_enrollment_info",
    "async_enrollment_submit",
    "organization_bootstrap",
    "ping",
]
