# Parsec Cloud (https://parsec.cloud) Copyright (c) BUSL-1.1 2016-present Scille SAS

# /!\ Autogenerated by misc/gen_protocol_typings.py, any modification will be lost !

from __future__ import annotations

from parsec._parsec import AsyncEnrollmentID, DateTime, PkiSignatureAlgorithm

class SubmitPayloadSignature:
    pass

class SubmitPayloadSignaturePKI(SubmitPayloadSignature):
    def __init__(
        self,
        signature: bytes,
        algorithm: PkiSignatureAlgorithm,
        submitter_der_x509_certificate: bytes,
        intermediate_der_x509_certificates: list[bytes],
    ) -> None: ...
    @property
    def algorithm(self) -> PkiSignatureAlgorithm: ...
    @property
    def intermediate_der_x509_certificates(self) -> list[bytes]: ...
    @property
    def signature(self) -> bytes: ...
    @property
    def submitter_der_x509_certificate(self) -> bytes: ...

class SubmitPayloadSignatureOpenBao(SubmitPayloadSignature):
    def __init__(self, signature: str, submitter_openbao_entity_id: str) -> None: ...
    @property
    def signature(self) -> str: ...
    @property
    def submitter_openbao_entity_id(self) -> str: ...

class Req:
    def __init__(
        self,
        enrollment_id: AsyncEnrollmentID,
        force: bool,
        submit_payload: bytes,
        submit_payload_signature: SubmitPayloadSignature,
    ) -> None: ...
    def dump(self) -> bytes: ...
    @property
    def enrollment_id(self) -> AsyncEnrollmentID: ...
    @property
    def force(self) -> bool: ...
    @property
    def submit_payload(self) -> bytes: ...
    @property
    def submit_payload_signature(self) -> SubmitPayloadSignature: ...

class Rep:
    @staticmethod
    def load(raw: bytes) -> Rep: ...
    def dump(self) -> bytes: ...

class RepUnknownStatus(Rep):
    def __init__(self, status: str, reason: str | None) -> None: ...
    @property
    def status(self) -> str: ...
    @property
    def reason(self) -> str | None: ...

class RepOk(Rep):
    def __init__(self, submitted_on: DateTime) -> None: ...
    @property
    def submitted_on(self) -> DateTime: ...

class RepEmailAlreadySubmitted(Rep):
    def __init__(self, submitted_on: DateTime) -> None: ...
    @property
    def submitted_on(self) -> DateTime: ...

class RepEmailAlreadyEnrolled(Rep):
    def __init__(
        self,
    ) -> None: ...

class RepIdAlreadyUsed(Rep):
    def __init__(
        self,
    ) -> None: ...

class RepInvalidSubmitPayload(Rep):
    def __init__(
        self,
    ) -> None: ...

class RepInvalidSubmitPayloadSignature(Rep):
    def __init__(
        self,
    ) -> None: ...

class RepInvalidDerX509Certificate(Rep):
    def __init__(
        self,
    ) -> None: ...

class RepInvalidX509Trustchain(Rep):
    def __init__(
        self,
    ) -> None: ...
